---
permalink: windows/concept_preinstallation_tasks.html 
sidebar: sidebar 
keywords: install, snapmanager, oracle, environment, preinstallation, task 
summary: Oracle용 SnapManager를 설치하기 전에 환경을 설정하기 위한 몇 가지 추가 작업을 수행해야 합니다. 수행해야 하는 작업은 운영 체제, Oracle 구성 요소 및 사용할 데이터베이스 버전에 따라 다릅니다. 
---
= 사전 설치 작업
:icons: font
:imagesdir: ../media/


[role="lead"]
Oracle용 SnapManager를 설치하기 전에 환경을 설정하기 위한 몇 가지 추가 작업을 수행해야 합니다. 수행해야 하는 작업은 운영 체제, Oracle 구성 요소 및 사용할 데이터베이스 버전에 따라 다릅니다.

* 적절한 패치를 사용하여 라이센스가 있는 운영 체제를 설치합니다.
* 운영 체제 및 Oracle 데이터베이스의 언어를 영어로 설정합니다.
+
예를 들어 Oracle 데이터베이스의 언어를 영어로 설정하려면 NLS_LANG=American_America.WE8MSWIN1252를 지정합니다. 언어를 설정하는 방법에 대한 자세한 내용은 _Troubleshooting SnapManager for Oracle_ 섹션을 참조하십시오.

* Oracle용 SnapManager와 함께 RMAN을 사용하려면 Oracle RMAN(Recovery Manager)을 설치합니다.
* 모든 스토리지 시스템에서 SnapRestore 및 FC(Fibre Channel), iSCSI(Internet Small Computer System Interface)와 같은 지원되는 프로토콜에 대해 활성화된 라이센스를 사용하여 Data ONTAP를 설치합니다.
* Oracle 데이터베이스 11.2.0.2 및 11.2.0.3을 사용하는 경우 다음 Oracle 패치를 설치합니다.
+
** 13413167(Windows 32비트)
** Windows 64비트용 13555974




* 관련 정보 *

xref:reference_troubleshooting_snapmanager.adoc[SnapManager 문제 해결]

http://support.netapp.com/NOW/products/interoperability/["NetApp 상호 운용성 매트릭스: support.netapp.com/NOW/products/interoperability"]

http://media.netapp.com/documents/tr-3761.pdf["SnapManager for Oracle 모범 사례: media.netapp.com/documents/tr-3761.pdf"]
