---
permalink: windows/delete_reference_trademark.html 
sidebar: sidebar 
keywords: trademark, information 
summary: 상표 정보 
---
= 상표 정보
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


Active IQ, AltaVault, Arch Design, ASUP, AutoSupport, Campaign Express, Clustered Data ONTAP, Customer Fitness, Data ONTAP, DataMotion, Element, Fitness, Flash Accel, Flash Cache, Flash Pool, FlexCache, FlexClone, FlexPod, FlexScale, FlexShare, FlexVol, FPolicy, Fueled by SolidFire, GetSuccessful, Helix Design, LockVault, Manage ONTAP, MetroCluster, MultiStore, NetApp, NetApp Insight, OnCommand, ONTAP, ONTAPI, RAID DP, RAID-TEC, SANscreen, SANshare, SANtricity, SecureShare, Simplicity, Simulate ONTAP, Snap Creator, SnapCenter, SnapCopy, SnapDrive, SnapIntegrator, SnapLock, SnapManager, SnapMirror, SnapMover, SnapProtect, SnapRestore, Snapshot, SnapValidator, SnapVault, SolidFire, SolidFire Helix, StorageGRID, SyncMirror, Tech OnTap, Unbound Cloud, WAFL 및 기타 이름은 미국 및/또는 기타 국가에서 NetApp, Inc.의 상표 또는 등록 상표입니다. 다른 모든 브랜드 또는 제품은 해당 소유자의 상표 또는 등록 상표이므로 그에 따라 취급해야 합니다. NetApp 상표의 현재 목록은 웹에서 확인할 수 있습니다.

http://www.netapp.com/us/legal/netapptmlist.aspx[]
