---
permalink: windows/reference_the_smosmsapbackup_mount_command.html 
sidebar: sidebar 
keywords: run, backup, mount, command, recover, operation, external 
summary: 백업 마운트 명령을 실행하여 백업을 마운트하면 외부 툴을 사용하여 복구 작업을 수행할 수 있습니다. 
---
= SMO 백업 마운트 명령
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
백업 마운트 명령을 실행하여 백업을 마운트하면 외부 툴을 사용하여 복구 작업을 수행할 수 있습니다.



== 구문

[listing]
----

        smo backup mount
-profile profile_name
[-label label \[-data \| -archivelogs\] \| \[-id id\]
[-host  host]

\[-dump\]
[-quiet | -verbose]
----


== 매개 변수

* * - profile profile_name *
+
마운트할 백업과 관련된 프로파일을 지정합니다. 프로파일에는 데이터베이스의 식별자와 기타 데이터베이스 정보가 들어 있습니다.

* * -id GUID *
+
지정된 GUID로 백업을 마운트합니다. GUID는 백업을 생성할 때 SnapManager에 의해 생성됩니다. SMO 백업 목록 명령을 사용하여 각 백업의 GUID를 표시할 수 있습니다.

* * - 라벨 라벨 *
+
지정된 레이블을 사용하여 백업을 마운트합니다.

* * -데이터 *
+
데이터 파일을 지정합니다.

* * -archivelogs *
+
아카이브 로그 파일을 지정합니다.

* * -호스트 호스트 *
+
백업을 마운트할 호스트를 지정합니다.

* * -덤프 *
+
마운트 작업이 성공하거나 실패한 후 덤프 파일을 수집합니다.

* * -저소음 *
+
콘솔에 오류 메시지만 표시합니다. 기본 설정은 오류 및 경고 메시지를 표시하는 것입니다.

* * - 자세한 정보 표시 *
+
콘솔에 오류, 경고 및 정보 메시지를 표시합니다.




NOTE: Oracle RMAN(Recovery Manager)과 같은 외부 툴을 사용하는 경우에만 이 명령을 사용해야 합니다. SnapManager는 SMO 백업 복원 명령을 사용하여 백업을 복원하는 경우 자동으로 백업 장착을 처리합니다. 이 명령은 스냅샷 복사본이 마운트된 경로를 보여 주는 목록을 표시합니다. 이 목록은 -verbose 옵션을 지정한 경우에만 표시됩니다.



== 예

다음 예에서는 백업을 마운트합니다.

[listing]
----
smo backup mount -profile SALES1 -label full_backup_sales_May -verbose
[INFO ]: SMO-13051: Process PID=6852
[INFO ]: SMO-13036: Starting operation Backup Mount on host hadley.domain.private
[INFO ]: SMO-13036: Starting operation Backup Mount on host hadley.domain.private
[INFO ]: SMO-13046: Operation GUID 8abc01573883daf0013883daf5ac0001 starting on Profile FAS_P1
[INFO ]: SD-00025: Beginning to connect filesystem(s) [I:\] from snapshot smo_fas_p1_fasdb_d_h_2_8abc0157388344bc01388344c2d50001_0.
[INFO ]: SD-00016: Discovering storage resources for C:\SnapManager_auto_mounts\I-2012071400592328_0.
[INFO ]: SD-00017: Finished storage discovery for C:\SnapManager_auto_mounts\I-2012071400592328_0
[INFO ]: SD-00026: Finished connecting filesystem(s) [I:\] from snapshot smo_fas_p1_fasdb_d_h_2_8abc0157388344bc01388344c2d50001_0.
[INFO ]: SD-00025: Beginning to connect filesystem(s) [H:\] from snapshot smo_fas_p1_fasdb_d_h_1_8abc0157388344bc01388344c2d50001_0.
[INFO ]: SD-00016: Discovering storage resources for C:\SnapManager_auto_mounts\H-2012071400592312_0.
[INFO ]: SD-00017: Finished storage discovery for C:\SnapManager_auto_mounts\H-2012071400592312_0.
[INFO ]: SD-00026: Finished connecting filesystem(s) [H:\] from snapshot smo_fas_p1_fasdb_d_h_1_8abc0157388344bc01388344c2d50001_0.
[INFO ]: SMO-13048: Backup Mount Operation Status: SUCCESS
[INFO ]: SMO-13049: Elapsed Time: 0:19:05.620
----
* 관련 정보 *

xref:task_mounting_backups.adoc[백업을 마운트하는 중입니다]
