---
permalink: windows/reference_the_smosmsap_repository_rollingback_command.html 
sidebar: sidebar 
keywords: command, enable, roll, back, revert, higher, version, original, version, upgrade, smo, repository 
summary: 이 명령을 사용하면 더 높은 버전의 SnapManager에서 업그레이드한 원래 버전으로 롤백하거나 되돌릴 수 있습니다. 
---
= SMO 리포지토리 롤백 명령
:icons: font
:imagesdir: ../media/


[role="lead"]
이 명령을 사용하면 더 높은 버전의 SnapManager에서 업그레이드한 원래 버전으로 롤백하거나 되돌릴 수 있습니다.



== 구문

[listing]
----

        smo repository rollback
-repository
-dbname repo_service_name
-host repo_host
-login -username repo_username
-port repo_port
-rollbackhost host_with_target_database
[-force]
\[-quiet \| -verbose\]
----


== 매개 변수

* * - 리포지토리 *
+
다음 리포지토리 옵션은 리포지토리의 데이터베이스 세부 정보를 지정합니다.

* * -dbname repo_service_name *
+
리포지토리를 저장하는 데이터베이스의 이름을 지정합니다. 글로벌 이름 또는 SID를 사용합니다.

* * -host repo_host *
+
리포지토리 데이터베이스가 실행되는 호스트 컴퓨터의 이름 또는 IP 주소를 지정합니다.

* * - 로그인 *
+
리포지토리 로그인 세부 정보를 시작합니다.

* * - 사용자 이름 repo_username *
+
리포지토리를 저장하는 데이터베이스에 액세스하는 데 필요한 사용자 이름을 지정합니다.

* * -Rollbackhost host host_with_target_database *
+
상위 버전의 SnapManager에서 원래 하위 버전으로 롤백될 호스트의 이름을 지정합니다.

* * -port repo_port *
+
리포지토리를 저장하는 데이터베이스에 액세스하는 데 사용되는 TCP 포트 번호를 지정합니다.

* * -force *
+
리포지토리 업데이트를 강제 적용합니다. SnapManager에서 업데이트하기 전에 현재 리포지토리를 백업하라는 메시지를 표시합니다.

* * -NOPrompt *
+
는 리포지토리 데이터베이스를 업데이트하기 전에 프롬프트를 표시하지 않습니다. not프롬프트 옵션을 사용하면 프롬프트가 나타나지 않으므로 스크립트를 사용하여 리포지토리를 쉽게 업데이트할 수 있습니다.

* * -저소음 *
+
콘솔에 오류 메시지만 표시합니다. 기본값은 오류 및 경고 메시지를 표시하는 것입니다.

* * - 자세한 정보 표시 *
+
콘솔에 오류, 경고 및 정보 메시지를 표시합니다.





== 명령 예

다음 예제에서는 SLESDB 데이터베이스의 저장소를 업데이트합니다.

[listing]
----
smo repository rollback -repository -dbname SALESDB
-host server1 -login -username admin -port 1521 -rollbackhost hostA
----