---
permalink: windows/reference_troubleshooting_known_issues.html 
sidebar: sidebar 
keywords: known, issues, snapmanager, troubleshooting 
summary: SnapManager를 사용할 때 발생할 수 있는 몇 가지 알려진 문제와 해결 방법을 알고 있어야 합니다. 
---
= 알려진 문제 해결
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapManager를 사용할 때 발생할 수 있는 몇 가지 알려진 문제와 해결 방법을 알고 있어야 합니다.



== SnapManager for Oracle이 클러스터 모드 프로파일을 식별하지 못합니다

SnapManager for Oracle 설치 디렉토리의 cmode_profiles.config 파일에 클러스터 모드 프로파일 이름이 없으면 다음 오류 메시지가 트리거될 수 있습니다.

SnapDrive config set-DFM user_name appliance_name을 사용하여 DFM 서버를 구성하십시오.

또한 Oracle용 SnapManager를 업그레이드하는 동안 /opt/netapp/smo/ * 폴더를 삭제하면 클러스터 모드 프로파일 이름이 인 cmode_profiles.config 파일도 삭제됩니다. 이 문제는 또한 동일한 오류 메시지를 트리거합니다.

* 해결 방법 *

프로필 업데이트: SMO 프로필 업데이트 - 프로필 <profile_name>


NOTE: Oracle용 SnapManager가 /opt/netapp/smo/경로에 설치된 경우 파일 위치는 /opt/netapp/smo/cmode_profile/cmode_profiles.config입니다.



== 서버가 시작되지 않습니다

서버를 시작할 때 다음과 유사한 오류 메시지가 나타날 수 있습니다.

SMO-01104: 명령 호출 오류: SMO-17107: 다음 오류로 인해 포트 8074에서 SnapManager 서버를 시작하지 못했습니다: java.net.BindException: 주소가 이미 사용 중입니다

이는 SnapManager 수신 대기 포트(기본적으로 27214 및 27215)가 현재 다른 응용 프로그램에서 사용되고 있기 때문일 수 있습니다.

이 오류는 SMO_server 명령이 이미 실행 중이지만 SnapManager가 기존 프로세스를 감지하지 못하는 경우에도 발생할 수 있습니다.

* 해결 방법 *

다른 포트를 사용하도록 SnapManager 또는 다른 애플리케이션을 재구성할 수 있습니다.

SnapManager를 재구성하려면 C:\Program Files\NetApp\SnapManager for Oracle\properties\SMO.config 파일을 편집하십시오

다음 값을 할당합니다.

* SMO Server.port = 27214
* SMO 서버.rmiRegistry.port = 27215
* remote.registry.socijdbc.port=27215
+
remote.registry.socijdbc.port는 Server.rmiRegistry.port와 같아야 합니다.



SnapManager 서버를 시작하려면 다음 단계를 수행하십시오.

. 시작 * > * 제어판 * > * 관리 도구 * > * 서비스 * 를 클릭합니다.
. 다음 세 가지 방법 중 하나로 서버를 시작할 수 있습니다.
+
** 왼쪽 패널에서 * 시작 * 을 클릭합니다.
** Oracle용 NetApp SnapManager 3.3을 마우스 오른쪽 단추로 클릭하고 드롭다운 메뉴에서 * 시작 * 을 선택합니다.
** Oracle용 NetApp SnapManager 3.3 을 두 번 클릭하고 속성 창이 열리면 * 시작 * 을 클릭합니다.






== 대상 이름이 다른 대상 이름의 일부인 경우 아카이브 로그 파일 대상 이름을 관리할 수 없습니다

아카이브 로그 백업을 생성하는 동안 사용자가 다른 대상 이름에 속하는 대상을 제외하는 경우 다른 대상 이름도 제외됩니다.

예를 들어, E:\\arch, G:\\arch, H:\\arch 등 세 가지 대상을 제외할 수 있다고 가정합니다. 아카이브 로그 파일 백업을 생성하는 동안 명령을 사용하여 E:\\arch를 제외할 경우

[listing]
----
smo backup create -profile almsamp1 -data -online -archivelogs  -exclude-dest E:\\arch
----
, Oracle용 SnapManager는 E:\\arch로 시작하는 모든 대상을 제외합니다.

* 해결 방법 *

* v$archive_dest에서 대상을 구성한 후 경로 구분 기호를 추가합니다. 예를 들어, E:\\arch를 E:\\arch\로 변경합니다.
* 백업을 생성하는 동안 대상을 제외하고 대상을 포함합니다.




== 저장소 데이터베이스 크기는 백업 수가 아닌 시간에 따라 증가합니다

SnapManager 작업은 저장소 데이터베이스 테이블의 스키마 내에서 데이터를 삽입하거나 삭제하므로 저장소 데이터베이스 크기가 시간이 지나면서 증가하므로 인덱스 공간 사용량이 높아집니다.

* 해결 방법 *

리포지토리 스키마에서 사용되는 공간을 제어하려면 Oracle 지침에 따라 인덱스를 모니터링하고 재구성해야 합니다.



== 리포지토리 데이터베이스가 다운된 경우 SnapManager GUI에 액세스할 수 없으며 SnapManager 작업이 실패합니다

SnapManager 작업이 실패하고 리포지토리 데이터베이스가 다운된 경우 GUI에 액세스할 수 없습니다.

다음 표에는 수행할 수 있는 여러 작업과 해당 예외 사항이 나열되어 있습니다.

|===


| 운영 | 예외 


 a| 
닫힌 리포지토리를 엽니다
 a| 
sm_gui.log에 다음 오류 메시지가 기록됩니다. [WARN]: smo-01106: 리포지토리를 쿼리하는 동안 오류가 발생했습니다. 종료된 연결 java.sql.SqlException: 종료된 연결.



 a| 
F5 키를 눌러 열려 있는 리포지토리를 새로 고칩니다
 a| 
리포지토리 예외는 GUI에 표시되며 sm_gui.log 파일에 NullPointerException도 기록합니다.



 a| 
호스트 서버를 새로 고치는 중입니다
 a| 
NullPointerException 은 sumo_gui.log 파일에 기록됩니다.



 a| 
새 프로파일 만들기
 a| 
프로필 구성 창에 NullPointerException 이 표시됩니다.



 a| 
프로파일을 새로 고치는 중입니다
 a| 
sm_gui.log에 다음 SQL 예외가 기록됩니다. [WARN]: smo-01106: 리포지토리를 쿼리하는 동안 오류가 발생했습니다. 닫힌 연결.



 a| 
백업에 액세스하는 중입니다
 a| 
sm_gui.log에 다음 오류 메시지가 기록됩니다. lazzily 수집 초기화 실패.



 a| 
클론 속성 보기
 a| 
sm_gui.log 및 sumo_GUI.log에 다음 오류 메시지가 기록됩니다. 수집을 lazily 초기화하지 못했습니다.

|===
* 해결 방법 *

GUI에 액세스하거나 SnapManager 작업을 수행하려는 경우 저장소 데이터베이스가 실행 중인지 확인해야 합니다.



== 복제된 데이터베이스에 대한 임시 파일을 생성할 수 없습니다

타겟 데이터베이스의 임시 테이블스페이스 파일이 데이터 파일의 마운트 지점이 아닌 마운트 지점에 배치된 경우 클론 생성 작업은 성공하지만 SnapManager는 클론 데이터베이스의 임시 파일을 생성하지 못합니다.

* 해결 방법 *

다음 중 하나를 수행해야 합니다.

* 임시 파일이 데이터 파일의 마운트 지점과 동일한 위치에 배치되도록 타겟 데이터베이스가 배치되었는지 확인합니다.
* 복제된 데이터베이스에 임시 파일을 수동으로 만들거나 추가합니다.




== Data Guard 대기 데이터베이스 백업 실패

보관 로그 위치가 기본 데이터베이스의 서비스 이름으로 구성된 경우 Data Guard 대기 데이터베이스 백업 작업이 실패합니다.

* 해결 방법 *

GUI에서 기본 데이터베이스의 서비스 이름에 해당하는 * 외부 아카이브 로그 위치 지정 * 의 선택을 해제해야 합니다.
