---
permalink: windows/reference_the_smosmsapbackup_update_command.html 
sidebar: sidebar 
keywords: run, backup, update, command, retention, policy, smo 
summary: 백업 업데이트 명령을 실행하여 백업 보존 정책을 업데이트할 수 있습니다. 
---
= SMO 백업 업데이트 명령
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
백업 업데이트 명령을 실행하여 백업 보존 정책을 업데이트할 수 있습니다.



== 구문

[listing]
----

        smo backup update
-profile profile_name
[-label label \[-data \| -archivelogs\] \| \[-id guid\]
\[-retain \{-hourly \| -daily \| -weekly \| -monthly \| -unlimited\}\]
\[-comment comment_text\]
[-quiet | -verbose]
----


== 매개 변수

* * - profile profile_name *
+
백업을 업데이트할 프로파일을 지정합니다. 프로파일에는 데이터베이스의 식별자와 기타 데이터베이스 정보가 들어 있습니다.

* * -id GUID *
+
지정된 GUID로 백업을 확인합니다. GUID는 백업을 생성할 때 SnapManager에 의해 생성됩니다. SMO 백업 목록 명령을 사용하여 각 백업의 GUID를 표시할 수 있습니다.

* * - 라벨 라벨 *
+
백업 레이블 및 백업 범위를 데이터 파일 또는 아카이브 로그로 지정합니다.

* * -데이터 *
+
데이터 파일을 지정합니다.

* * -archivelogs *
+
아카이브 로그 파일을 지정합니다.

* * - 코멘트 코멘트_텍스트 *
+
백업 업데이트에 대한 텍스트(최대 200자)를 입력합니다. 공백을 포함할 수 있습니다.

* * -저소음 *
+
콘솔에 오류 메시지만 표시합니다. 기본값은 오류 및 경고 메시지를 표시하는 것입니다.

* * - 자세한 정보 표시 *
+
콘솔에 오류, 경고 및 정보 메시지를 표시합니다.

* * - 유지 {-hourly|-daily|-weekly|-monthly|-limited} *
+
백업을 매시간, 매일, 매주, 매월 또는 무제한 단위로 보존할지 여부를 지정합니다. retain을 지정하지 않으면 보존 클래스의 기본값은 -hourly입니다. 백업을 영구적으로 보존하려면 -unlimited 옵션을 사용합니다. 무제한 옵션을 사용하면 백업이 삭제되지 않습니다.





== 예

다음 예에서는 보존 정책을 무제한으로 설정할 백업을 업데이트합니다.

[listing]
----
smo backup update -profile SALES1 -label full_backup_sales_May
-retain -unlimited -comment save_forever_monthly_backup
----
* 관련 정보 *

xref:task_changing_the_backup_retention_policy.adoc[백업 보존 정책 변경]

xref:task_retaining_backups_forever.adoc[백업을 영구적으로 유지합니다]

xref:task_freeing_or_deleting_retention_policy_exempt_backups.adoc[보존 정책 제외 백업을 해제 또는 삭제합니다]
