---
permalink: windows/reference_the_smosmsapclone_create_command.html 
sidebar: sidebar 
keywords: clone, create, command, backed, up, database, primary, secondary, storage, smo 
summary: clone create 명령을 실행하여 백업된 데이터베이스의 클론을 생성할 수 있습니다. 기본 또는 보조 스토리지에서 백업을 클론 복제할 수 있습니다. 
---
= SMO 복제 create 명령
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
clone create 명령을 실행하여 백업된 데이터베이스의 클론을 생성할 수 있습니다. 기본 또는 보조 스토리지에서 백업을 클론 복제할 수 있습니다.



== 구문

[listing]
----

        smo clone create
-profile profile_name
[-backup-id backup_guid \| -backup-label backup_label_name \| -current\]
-newsid new_sid
\[-host target_host\]
[-label clone_label]
\[-comment string\]
-clonespec full_path_to_clonespec_file
]
\[-syspassword syspassword\]
\[-reserve \{yes \| no \| inherit\}\]

\[-no-resetlogs \| -recover-from-location path1 \[, path2\]\]\[-taskspec taskspec\]
\[-dump\]
\[-quiet \| -verbose\]
----


== 매개 변수

* * - 프로파일 이름 *
+
복제할 데이터베이스를 지정합니다. 프로파일에는 데이터베이스의 식별자와 기타 데이터베이스 정보가 들어 있습니다.

* * -backup-id GUID *
+
지정된 GUID를 사용하여 백업을 복제합니다. GUID는 백업을 생성할 때 SnapManager에 의해 생성됩니다. SMO backup list -verbose 명령을 사용하여 각 백업의 GUID를 표시할 수 있습니다.

* * -backup-label backup_label_name *
+
지정된 레이블 이름을 사용하여 백업을 복제하도록 지정합니다.

* * - 현재 *
+
데이터베이스의 현재 상태에서 백업 및 클론을 생성하도록 지정합니다.

+

NOTE: 데이터베이스가 narchivelog 모드인 경우 SnapManager는 오프라인 백업을 생성합니다.

* * -newsid new_sid *
+
복제된 데이터베이스에 대한 고유한 새 Oracle 시스템 식별자를 지정합니다. 시스템 식별자 값은 최대 8자입니다. Oracle은 동일한 호스트에서 동일한 시스템 식별자를 갖는 두 개의 데이터베이스를 동시에 실행할 수 없습니다.

* * -host target_host *
+
클론을 생성할 호스트를 지정합니다.

* * -label clone_label *
+
클론의 레이블을 지정합니다.

* * - 주석 문자열 *
+
이 클론을 설명할 선택적 주석을 지정합니다. 문자열을 작은따옴표로 묶어야 합니다.

+

NOTE: 일부 쉘은 따옴표를 삭제합니다. 셸에 대해 참인 경우 큰따옴표(\)를 백슬래시(\)로 이스케이프해야 합니다. 예를 들어, 다음과 같이 입력해야 할 수 있습니다. \'이것은 코멘트\'입니다.

* * -clonespec full_path_to_clonespec_file *
+
클론 사양 XML 파일의 경로를 지정합니다. 상대 경로 또는 절대 경로 이름이 될 수 있습니다.

* syspassword syspassword *
+
시스템 권한이 있는 사용자의 암호를 지정합니다.

+

NOTE: 제공된 데이터베이스 자격 증명이 시스템 권한 사용자에 대해 동일하지 않은 경우 시스템 권한 사용자의 암호를 제공해야 합니다.

* * -예비 *
+
reserve 옵션을 yes로 설정하면 새 클론 볼륨에 대해 볼륨 보증 공간 예비 공간이 설정됩니다. reserve 옵션을 no로 설정하면 새 클론 볼륨에 대해 볼륨 보증 공간 예약이 해제됩니다. inherit에 -reserve 옵션을 설정하면 새 클론이 부모 스냅샷 복사본의 공간 예약 특성을 상속합니다. 기본 설정은 아니오입니다

+
다음 표에서는 클론 생성 방법과 클론 생성 작업 및 해당 예약 옵션에 미치는 영향에 대해 설명합니다. 두 방법 중 하나를 사용하여 LUN을 클론 복제할 수 있습니다.

+
|===


| 복제 방법입니다 | 설명 | 결과 


 a| 
 LUN cloning a| 
 A new clone LUN is created within the same volume. a| 
 When the -reserve option for a LUN is set to yes, space is reserved for the full LUN size within the volume.


 a| 
 Volume cloning a| 
 A new FlexClone is created, and the clone LUN exists within the new clone volume. Uses the FlexClone technology. a| 
 When the -reserve option for a volume is set to yes, space is reserved for the full volume size within the aggregate.
를 누릅니다

|===
* * -재설정 로그 없음 *
+
데이터베이스 복구를 건너뛰고 DBNEWID 유틸리티를 실행하며 클론을 생성하는 동안 resetlogs를 사용하여 데이터베이스를 열지 않도록 지정합니다.

* * -복구 위치 *
+
SnapManager가 외부 위치에서 아카이브 로그 파일을 가져와 클론 생성에 사용하는 아카이브 로그 백업의 외부 아카이브 로그 위치를 지정합니다.

* * - 작업 사양 *
+
클론 작업의 사전 처리 작업 또는 사후 처리 작업에 대한 작업 사양 XML 파일을 지정합니다. 작업 사양 XML 파일의 전체 경로를 제공해야 합니다.

* * -덤프 *
+
클론 생성 작업 후 덤프 파일을 수집하도록 지정합니다.

* * -저소음 *
+
콘솔에 오류 메시지만 표시합니다. 기본 설정은 오류 및 경고 메시지를 표시하는 것입니다.

* * - 자세한 정보 표시 *
+
콘솔에 오류, 경고 및 정보 메시지를 표시합니다.





== 예

다음 예에서는 이 클론에 대해 생성된 클론 사양을 사용하여 백업을 복제합니다.

[listing]
----
smo clone create -profile SALES1 -backup-label full_backup_sales_May -newsid
CLONE -label sales1_clone -clonespec E:\\spec\\clonespec.xml
----
[listing]
----
Operation Id [8abc01ec0e794e3f010e794e6e9b0001] succeeded.
----
* 관련 정보 *

xref:task_creating_clone_specifications.adoc[클론 사양 생성 중]

xref:task_cloning_databases_from_backups.adoc[백업에서 데이터베이스 클론 생성]
