---
permalink: unix-administration/concept_requirements_for_using_asm_databases_with_snapmanager.html 
sidebar: sidebar 
keywords: automatic, storage, management, asm, snapmanager, database, snapmanager, 
summary: 'SnapManager와 함께 자동 스토리지 관리(ASM) 데이터베이스를 사용하기 위한 요구 사항을 알고 있어야 합니다. 이러한 요구 사항을 알면 ASMLib, 파티션 및 복제 사양과 관련된 문제를 방지할 수 있습니다.' 
---
= SnapManager와 함께 ASM 데이터베이스를 사용하기 위한 요구 사항
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapManager와 함께 자동 스토리지 관리(ASM) 데이터베이스를 사용하기 위한 요구 사항을 알고 있어야 합니다. 이러한 요구 사항을 알면 ASMLib, 파티션 및 복제 사양과 관련된 문제를 방지할 수 있습니다.

* SnapManager(3.0.3 이상)은 sysdba 권한 대신 Oracle 11gR2에서 사용할 수 있는 새로운 sysasm 권한을 사용하여 Oracle ASM 인스턴스를 관리합니다.
+
sysdba 권한을 사용하여 ASM 인스턴스에서 관리 명령을 실행하면 오류 메시지가 표시됩니다. 데이터베이스는 sysdba 권한을 사용하여 디스크 그룹에 액세스합니다. sysasm 권한을 사용하여 ASM 인스턴스에 연결하는 경우 사용 가능한 모든 Oracle ASM 디스크 그룹 및 관리 기능에 완전히 액세스할 수 있습니다.

+

NOTE: Oracle 10gR2 및 11gR1을 사용하는 경우 sysdba 권한을 계속 사용해야 합니다.

* SnapManager(3.0.3 이상)는 디스크 그룹에 ACFS(자동 클러스터 파일 시스템) 볼륨도 포함되어 있을 때 ASM 디스크 그룹에 직접 저장되는 데이터베이스 백업을 지원합니다.
+
이러한 파일은 SnapManager에 의해 간접적으로 보호되며 ASM 디스크 그룹의 나머지 내용으로 복구될 수 있지만 SnapManager(3.0.3 이상)은 ACFS를 지원하지 않습니다.

+

NOTE: ACFS는 Oracle 11gR2와 함께 사용할 수 있는 확장 가능한 다중 플랫폼 파일 시스템 스토리지 관리 기술입니다. ACFS는 ASM 기능을 확장하여 Oracle 데이터베이스 외부에서 유지 관리되는 고객 파일을 지원합니다.

* SnapManager(3.0.3 이상)는 디스크 그룹에 Oracle 클러스터 레지스트리(OCR) 파일 또는 보팅 디스크 파일도 포함되어 있을 때 ASM 디스크 그룹에 저장되는 파일의 백업을 지원합니다. 그러나 복구 작업에는 더 느린 호스트 기반 또는 부분 파일 스냅 복원(PFSR) 방법이 필요합니다.
+
데이터베이스 파일이 없는 디스크 그룹에 OCR 및 보팅 디스크를 사용하는 것이 가장 좋습니다.

* ASM에 사용되는 각 디스크는 하나의 파티션만 포함해야 합니다.
* 심각한 성능 문제를 방지하려면 ASM 데이터를 호스팅하는 파티션이 올바르게 정렬되어야 합니다.
+
이는 LUN이 올바른 유형이어야 하며 파티션에 4K 바이트의 배수인 오프셋이 있어야 함을 의미합니다.

+

NOTE: 4K로 정렬된 파티션을 만드는 방법에 대한 자세한 내용은 기술 자료 문서 101010717을 참조하십시오.

* ASM 구성은 클론 사양의 일부로 지정되지 않습니다.
+
호스트를 SnapManager(2.2 이상)로 업그레이드하기 전에 SnapManager 2.1을 사용하여 생성한 클론 사양의 ASM 구성 정보를 수동으로 제거해야 합니다.

* SnapManager 3.1, 3.1p1 및 3.2 이상은 ASMLib 2.1.4를 지원합니다.
* SnapManager 3.1p4 이상은 ASMLib 2.1.4, 2.1.7 및 2.1.8을 지원합니다.

