---
permalink: unix-administration/reference_the_smosmsapclone_delete_command.html 
sidebar: sidebar 
keywords: run, clone, delete, command, operation, smo 
summary: clone delete 명령을 실행하여 클론을 삭제할 수 있습니다. 클론이 작업에서 사용 중인 경우에는 클론을 삭제할 수 없습니다. 
---
= SMO 복제 삭제 명령
:icons: font
:imagesdir: ../media/


[role="lead"]
clone delete 명령을 실행하여 클론을 삭제할 수 있습니다. 클론이 작업에서 사용 중인 경우에는 클론을 삭제할 수 없습니다.



== 구문

[listing]
----

        smo clone delete
-profile profile_name
\[-id guid \| -label clone_name\]
[-login
\[-username db_username -password db_password -port db_port\]
 \[-asminstance -asmusername asminstance_username  -asmpassword asminstance_password\]]
\[-syspassword syspassword\]
-force
\[-dump\]
\[-quiet \| -verbose\]
----


== 매개 변수

* * - profile profile_name *
+
삭제할 클론이 포함된 프로필의 이름을 지정합니다. 프로파일에는 데이터베이스의 식별자와 기타 데이터베이스 정보가 들어 있습니다.

* * -force *
+
클론과 연결된 리소스가 있는 경우에도 클론을 삭제합니다.

* * -id GUID *
+
삭제할 클론의 GUID를 지정합니다. GUID는 클론을 생성할 때 SnapManager에 의해 생성됩니다. SMO 클론 목록 명령을 사용하여 각 클론의 GUID를 표시할 수 있습니다.

* * - 라벨 이름 *
+
삭제할 클론의 레이블을 지정합니다.

* * -asminstance *
+
ASM(Automatic Storage Management) 인스턴스에 로그인하는 데 사용되는 자격 증명을 지정합니다.

* * - asmusername asminstance_username *
+
ASM 인스턴스에 로그인하는 데 사용되는 사용자 이름을 지정합니다.

* * -asmpassword asminstance_password *
+
ASM 인스턴스에 로그인하는 데 사용되는 암호를 지정합니다.

* syspassword syspassword *
+
시스템 권한이 있는 사용자의 암호를 지정합니다.

+

NOTE: 제공된 데이터베이스 자격 증명이 시스템 권한 사용자의 자격 증명과 동일하지 않은 경우 시스템 권한 사용자의 암호를 제공해야 합니다.

* * - 로그인 *
+
데이터베이스 로그인 정보를 입력할 수 있습니다.

* * - 사용자 이름 db_username *
+
데이터베이스에 액세스하는 데 필요한 사용자 이름을 지정합니다.

* * - 암호 db_password *
+
데이터베이스에 액세스하는 데 필요한 암호를 지정합니다.

* * -포트 db_port *
+
프로파일이 설명하는 데이터베이스에 액세스하는 데 사용되는 TCP 포트 번호를 지정합니다.

* * -덤프 *
+
클론 삭제 작업 후 덤프 파일을 수집하도록 지정합니다.

* * -저소음 *
+
콘솔에 오류 메시지만 표시합니다. 기본값은 오류 및 경고 메시지를 표시하는 것입니다.

* * - 자세한 정보 표시 *
+
콘솔에 오류, 경고 및 정보 메시지를 표시합니다.





== 예

다음 예제에서는 클론을 삭제합니다.

[listing]
----
smo clone delete -profile SALES1 -label SALES_May
Operation Id [8abc01ec0e79004b010e79006da60001] succeeded.
----