---
permalink: unix-administration/reference_mounting_a_flexclone_fails_in_nfs_environment.html 
sidebar: sidebar 
keywords: snapmanager, flexclone, volume, nfs, environment, clone, backup, flexvol, ha, pair, configuration, export 
summary: SnapManager가 NFS 환경에서 볼륨의 FlexClone을 생성하면 /etc/exports 파일에 항목이 추가됩니다. 클론 또는 백업이 SnapManager 호스트에 마운트되지 못하고 오류 메시지가 표시됩니다. 
---
= NFS 환경에서 FlexClone 볼륨을 마운트할 수 없습니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapManager가 NFS 환경에서 볼륨의 FlexClone을 생성하면 /etc/exports 파일에 항목이 추가됩니다. 클론 또는 백업이 SnapManager 호스트에 마운트되지 못하고 오류 메시지가 표시됩니다.

오류 메시지는 다음과 같습니다. 0001-034 명령 오류: 마운트 실패: filer1:/vol/SnapManager_20090914112850837_vol14 on/opt/NTAPsmo/mnt/-ora_data02-20090914112850735_1 - 경고 알 수 없는 옵션 "zone=vol14" NFS 마운트: filer1:/vol149091014_vol149014/s4_vol149014_s200/s200/s200-149014.

동시에 스토리지 시스템 콘솔에서 다음 메시지가 생성됩니다. Mon Sep 14 23:58:37 PDT [filer1:export.auto.update.disabled: 경고]: /etc/exports는 vol clone create 명령을 실행할 때 vol14에 대해 업데이트되지 않았습니다. /etc/exports를 수동으로 업데이트하거나 /etc/exports.new를 복사합니다.

이 메시지는 AutoSupport 메시지에서 캡처되지 않을 수 있습니다.


NOTE: NFS에서 FlexVol 볼륨을 클론 복제하는 동안 유사한 문제가 발생할 수 있습니다. 동일한 단계를 따라 nfs.export.auto-update 옵션을 활성화할 수 있습니다.

* 해야 할 일 *

. /etc/exports 파일이 자동으로 업데이트되도록 nfs.export.auto-update 옵션을 설정합니다. 옵션 nfs.export.auto-updateon



NOTE: HA 쌍 구성에서 두 스토리지 시스템 모두에 대해 NFS 엑스포트 옵션을 켜짐으로 설정해야 합니다.
