---
permalink: unix-administration/reference_the_smosmsapcredential_delete_command.html 
sidebar: sidebar 
keywords: command, delete, user, credential, particular, secure, resource, smo 
summary: 이 명령은 특정 보안 리소스에 대한 사용자 자격 증명을 삭제합니다. 
---
= SMO 자격 증명 삭제 명령
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
이 명령은 특정 보안 리소스에 대한 사용자 자격 증명을 삭제합니다.



== 구문

[listing]
----

        smo credential delete
\[-host -name host_name
-username username\] \|
[-repository
-dbname repo_service_name
-host repo_host
-login -username repo_username
-port repo_port\] \|
\[-profile
-name profile_name\]
[-quiet | -verbose]
----


== 매개 변수

* * -호스트 호스트 호스트 이름 *
+
SnapManager가 실행 중인 호스트 서버의 이름을 지정합니다.

+
host 매개 변수에는 다음 옵션이 포함됩니다.

+
** -name host_name: 암호를 삭제할 호스트의 이름을 지정합니다.
** 사용자 이름 user_name: 호스트의 사용자 이름을 지정합니다.


* * -repository-dbname * 입니다
+
프로필을 저장하는 데이터베이스의 이름을 지정합니다. 글로벌 이름 또는 SID를 사용합니다.

+
repository 매개 변수에는 다음 옵션이 포함되어 있습니다.

+
** -dbnamerepo_service_name: 프로파일을 저장하는 데이터베이스의 이름을 지정합니다. 글로벌 이름 또는 SID를 사용합니다.
** -host repo_host: 저장소 데이터베이스가 실행되는 호스트 서버의 이름 또는 IP 주소를 지정합니다.
** -login-username repo_username: 리포지토리를 저장하는 데이터베이스에 액세스하는 데 필요한 사용자 이름을 지정합니다.
** -port repo_port: 리포지토리를 저장하는 데이터베이스에 액세스하는 데 사용되는 TCP 포트 번호를 지정합니다.


* * -profile-name profile_name *
+
데이터베이스가 연결된 프로파일을 지정합니다.

+
profile 매개변수에는 다음 옵션이 포함되어 있습니다.

+
** -name profilename: 암호를 삭제할 프로필의 이름을 지정합니다.


* * -저소음 *
+
콘솔에 오류 메시지만 표시합니다. 기본값은 오류 및 경고 메시지를 표시하는 것입니다.

* * - 자세한 정보 표시 *
+
콘솔에 오류, 경고 및 정보 메시지를 표시합니다.





== 명령 예

이 예제에서는 프로파일의 자격 증명을 삭제합니다.

[listing]
----
smo credential delete -profile -name user1 -verbose
----
[listing]
----
SMO-20022 [INFO ]: Deleted credentials and repository mapping
 for profile "user1" in user credentials for "user1".
----
이 예제에서는 리포지토리의 자격 증명을 삭제합니다.

[listing]
----
smo credential delete -repository -dbname SMOREPO -host Host2
-login -username user1 -port 1521
----
[listing]
----
SMO-20023 [INFO ]: Deleted repository credentials for "user1@SMOREPO/wasp:1521"
and associated profile mappings in user credentials for "user1".
----
이 예제에서는 호스트의 자격 증명을 삭제합니다.

[listing]
----
smo credential delete -host -name Host2
----
[listing]
----
SMO-20033 [INFO ]: Deleted host credentials for "Host2" in user credentials for "user1".
----
* 관련 정보 *

xref:task_deleting_credentials_for_individual_resources.adoc[개별 리소스에 대한 자격 증명을 삭제하는 중입니다]
