---
permalink: unix-administration/reference_snapmanager_configuration_parameters.html 
sidebar: sidebar 
keywords: snapmanager, configuration, parameters, requirement, retain, hourly, monthly, count, duration 
summary: SnapManager는 요구 사항에 따라 편집할 수 있는 구성 매개 변수 목록을 제공합니다. 구성 매개 변수는 SMO.config 파일에 저장됩니다. 그러나 SMO.config 파일에는 지원되는 구성 매개 변수가 모두 포함되어 있지 않을 수 있습니다. 요구 사항에 따라 구성 매개 변수를 추가할 수 있습니다. 
---
= SnapManager 구성 매개 변수
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapManager는 요구 사항에 따라 편집할 수 있는 구성 매개 변수 목록을 제공합니다. 구성 매개 변수는 SMO.config 파일에 저장됩니다. 그러나 SMO.config 파일에는 지원되는 구성 매개 변수가 모두 포함되어 있지 않을 수 있습니다. 요구 사항에 따라 구성 매개 변수를 추가할 수 있습니다.

다음 표에는 지원되는 모든 SnapManager 구성 매개 변수가 나열되어 있으며 이러한 매개 변수를 사용해야 하는 경우도 나와 있습니다.

|===


| 매개 변수 | 설명 


 a| 
* hourly.count를 유지합니다
* 시간당 유지 기간
* 월별 보존. 수
* 월별 유지 기간

 a| 
이러한 매개 변수는 프로파일을 생성할 때 보존 정책을 설정합니다. 예를 들어, retain.hourly.count=12 값을 할당할 수 있습니다

hourly.duration=2

매월 .count=2

매월 유지. 기간 = 6



 a| 
restore.secondaryAccessPolicy
 a| 
이 매개 변수는 SnapManager에서 Protection Manager를 사용하여 직접 복구할 수 없는 경우 보조 스토리지의 데이터에 액세스하는 방법을 정의합니다. 보조 스토리지의 데이터에 액세스하는 다양한 방법은 다음과 같습니다.

* 직접(기본값)
+
restore.secondaryAccessPolicy 가 direct로 설정되어 있으면 SnapManager는 보조 스토리지에 있는 데이터를 복제하고, 보조 스토리지에서 호스트로 클론 복제된 데이터를 마운트한 다음 클론 데이터를 활성 환경에 복사합니다.

* 간접
+
restore.secondaryAccessPolicy 에 간접 을 할당하는 경우 SnapManager는 데이터를 운영 스토리지의 임시 볼륨에 복사하고, 임시 볼륨의 데이터를 호스트에 마운트한 다음, 임시 볼륨의 데이터를 활성 환경에 복사합니다.

+
간접 방법은 호스트에 보조 스토리지 시스템에 대한 직접 액세스 권한이 없는 경우에만 사용해야 합니다. 이 방법은 두 개의 데이터 복사본이 만들어지기 때문에 직접 방법보다 두 배 더 오래 걸립니다.




NOTE: NFS(네트워크 파일 시스템)를 프로토콜로 사용하는 SAN(Storage Area Network)에서 SnapManager는 복구를 수행하기 위해 보조 스토리지에 직접 연결할 필요가 없습니다.



 a| 
restore.temporaryVolumeName을 참조하십시오
 a| 
이 매개 변수는 임시 볼륨에 이름을 할당합니다. SnapManager가 보조 스토리지에서 데이터를 복원하는 간접 방법을 사용하는 경우, 데이터가 데이터베이스 파일에 복사되고 데이터베이스가 복구될 때까지 기본 스토리지의 스크래치 볼륨이 데이터의 임시 복사본을 보류해야 합니다. 기본값이 없습니다. 값을 지정하지 않으면 간접 방법을 사용하는 restore 명령에 이름을 입력해야 합니다. 예를 들어 restore.temporaryVolumeName=smo_temp_volume 값을 할당할 수 있습니다



 a| 
Retain.al방식 FreeExpiredBackups를 선택합니다
 a| 
이 매개 변수를 사용하면 데이터 보호가 구성되지 않은 경우에도 SnapManager에서 백업이 만료되었을 때와 빠른 복원이 수행될 때 백업을 사용할 수 있습니다. 이 매개 변수는 만료되고 만료되는 보호되지 않은 백업을 만료 및 삭제하는 보호된 백업을 해제합니다. 지정할 수 있는 값은 다음과 같습니다.

* 참
+
TRUE를 할당하여 retain.alassemblyExpiredBackups를 지정하면 SnapManager는 백업이 보호되는지 여부에 관계없이 만료된 백업을 해제합니다.

+
백업이 보호되지 않거나 보조 스토리지의 보호된 복제본도 만료된 경우 백업이 삭제됩니다.

* 거짓
+
false 를 할당하여 retain.alassemblyExpiredBackups 를 지정하면 SnapManager 는 보호되는 만료된 백업을 해제합니다.





 a| 
host.credentials.persist를 입력합니다
 a| 
이 매개 변수를 사용하면 SnapManager에서 호스트 자격 증명을 저장할 수 있습니다. 기본적으로 호스트 자격 증명은 저장되지 않습니다. 그러나 원격 클론에서 실행되는 사용자 지정 스크립트가 있고 원격 서버에 액세스해야 하는 경우에는 호스트 자격 증명을 저장해야 합니다. host.credentials.persist 에 true 를 할당하여 호스트 자격 증명 저장을 활성화할 수 있습니다. SnapManager는 호스트 자격 증명을 암호화하고 저장합니다.



 a| 
RestorePlanMaxFilesDisplor되었습니다
 a| 
이 매개 변수를 사용하면 복원 미리 보기에 표시할 최대 파일 수를 정의할 수 있습니다. 기본적으로 SnapManager에서는 복원 미리 보기에 최대 20개의 파일을 표시합니다. 그러나 0보다 큰 값으로 변경할 수 있습니다. 예를 들어, 다음 값을 할당할 수 있습니다.

* RestorePlanMaxFilesDisplor됨 = 30



NOTE: 잘못된 값을 지정하면 기본 파일 수가 표시됩니다.



 a| 
snapshot.list.timeout.min
 a| 
이 매개 변수를 사용하면 SnapManager 작업을 수행할 때 SnapManager에서 snap list 명령이 실행될 때까지 기다려야 하는 시간을 분 단위로 정의할 수 있습니다. 기본적으로 SnapManager는 30분 동안 대기합니다. 그러나 0보다 큰 값으로 변경할 수 있습니다. 예를 들어, 다음 값을 할당할 수 있습니다.

* snapshot.list.timeout.min = 40



NOTE: 잘못된 값을 지정하면 기본값이 사용됩니다.

SnapManager 작업의 경우 snap list 명령 실행 시간이 snapshot.list.timeout.min에 할당된 값을 초과하면 시간 초과 오류 메시지와 함께 작업이 실패합니다.



 a| 
CuteIfFileExistsInOtherDestination 을 참조하십시오
 a| 
이 잘라내기 매개 변수를 사용하면 보관 로그 파일의 대상을 정의할 수 있습니다. 아카이브 로그 파일은 여러 대상에 저장됩니다. 아카이브 로그 파일을 보관하는 동안 SnapManager는 아카이브 로그 파일의 대상을 알아야 합니다. 지정할 수 있는 값은 다음과 같습니다.

* 지정된 대상에서 아카이브 로그 파일을 정리하려면 pruneIfFileExistsInOtherDestination 에 false 를 할당해야 합니다.
* 외부 대상에서 아카이브 로그 파일을 정리하려면 pruneIfFileExistsInOtherDestination 에 true 를 할당해야 합니다.




 a| 
prune.archivelogs.backedup.from.otherdestination
 a| 
이 잘라내기 매개 변수를 사용하면 지정된 아카이브 로그 대상에서 백업되거나 외부 아카이브 로그 대상에서 백업된 아카이브 로그 파일을 정리할 수 있습니다. 지정할 수 있는 값은 다음과 같습니다.

* 지정된 대상에서 아카이브 로그 파일을 정리하려는 경우 -prune-dest를 사용하여 지정된 대상에서 아카이브 로그 파일을 백업하면 prune.archivelogs.backedup.from.otherdestination 에 false를 할당해야 합니다.
* 지정된 대상에서 보관 로그 파일을 정리하려는 경우 보관 로그 파일이 다른 대상에서 한 번 이상 백업되는 경우 prune.archivelogs.backedup.from.otherdestination 에 true 를 할당해야 합니다.




 a| 
Maximum.archivelog.files.toprune.atATime입니다
 a| 
이 잘라내기 매개 변수를 사용하면 지정된 시간에 정리할 수 있는 최대 아카이브 로그 파일 수를 정의할 수 있습니다. 예를 들어, maximum.archivelog.files.toprune.atATime=998 값을 할당할 수 있습니다


NOTE: maximum.archivelog.files.toprune.atATime에 할당할 수 있는 값은 1000보다 작아야 합니다.



 a| 
아카이브 통합
 a| 
archivelogs.Consolidate에 true를 할당할 경우 이 매개 변수를 통해 SnapManager에서 중복 아카이브 로그 백업을 사용할 수 있습니다.



 a| 
접미사 .backup.label.with.logs
 a| 
이 매개 변수를 사용하면 데이터 백업 및 아카이브 로그 백업의 레이블 이름을 구별하기 위해 추가할 접미사를 지정할 수 있습니다. 예를 들어 suffix.backup.label.with.logs에 로그를 할당할 때 _logs가 아카이브 로그 백업 레이블에 접미사로 추가됩니다. 아카이브 로그 백업 레이블은 ARCH_LOGS입니다.



 a| 
backup.archivelogs.beyond.missingfiles
 a| 
이 매개 변수를 사용하면 SnapManager에서 누락된 아카이브 로그 파일을 백업에 포함할 수 있습니다. 활성 파일 시스템에 없는 아카이브 로그 파일은 백업에 포함되지 않습니다. 활성 파일 시스템에 없는 아카이브 로그 파일을 포함하여 모든 아카이브 로그 파일을 포함하려면 backup.archivelogs.beyond.missingfiles 에 true 를 할당해야 합니다.

누락된 아카이브 로그 파일을 무시하도록 false를 할당할 수 있습니다.



 a| 
srvctl.timeout을 참조하십시오
 a| 
이 매개 변수를 사용하면 srvctl 명령에 대한 시간 초과 값을 정의할 수 있습니다. * 참고:* 서버 컨트롤(SRVCTL)은 RAC 인스턴스를 관리하는 유틸리티입니다.

SnapManager가 timeout 값보다 srvctl 명령을 실행하는 데 시간이 더 오래 걸리는 경우 SnapManager 작업이 실패하고 다음 오류 메시지가 표시됩니다. Error: timeout occurred while execute command: srvctl status.



 a| 
snapshot.restore.storageNameCheck 를 참조하십시오
 a| 
이 매개 변수를 사용하면 SnapManager에서 7-Mode의 Data ONTAP에서 clustered Data ONTAP으로 마이그레이션하기 전에 생성된 스냅샷 복사본을 사용하여 복원 작업을 수행할 수 있습니다. 매개 변수에 할당된 기본값은 false 입니다. 7-Mode에서 운영되는 Data ONTAP을 clustered Data ONTAP으로 마이그레이션했지만 마이그레이션 전에 생성된 스냅샷 복사본을 사용하려면 snapshot.restore.storageNameCheck=true를 설정합니다.



 a| 
services.common.disableAbort
 a| 
이 매개 변수는 장기 실행 작업 실패 시 정리를 비활성화합니다. services.common.disableAbort=true.For 예를 설정할 수 있습니다. Oracle 오류로 인해 오래 실행된 후 실패한 클론 작업을 수행하는 경우 클론을 정리하지 않을 수 있습니다. services.common.disableAbort=true 를 설정하면 클론이 삭제되지 않습니다. Oracle 문제를 해결하고 실패한 지점에서 클론 작업을 다시 시작할 수 있습니다.



 a| 
* backup.sleep.dnfs.layout을 참조하십시오
* backup.sleep.dnfs.secs

 a| 
이러한 매개 변수는 dNFS(Direct NFS) 레이아웃에서 절전 메커니즘을 활성화합니다. dNFS 또는 NFS(네트워크 파일 시스템)를 사용하여 제어 파일의 백업을 생성한 후 SnapManager는 제어 파일을 읽으려고 하지만 파일을 찾을 수 없습니다. 절전 메커니즘을 활성화하려면 backup.sleep.dnfs.layout=true를 확인하십시오. 기본값은 true 입니다.

슬립 메커니즘을 활성화할 때 backup.sleep.dnfs.secs 에 수면 시간을 할당해야 합니다. 할당된 대기 시간은 초 단위로 되어 있으며 값은 환경에 따라 다릅니다. 기본값은 5초입니다.

예를 들면 다음과 같습니다.

* backup.sleep.dnfs.layout=true입니다
* backup.sleep.dnfs.secs=2




 a| 
* override.default.backup.pattern
* new.default.backup.pattern

 a| 
백업 레이블을 지정하지 않으면 SnapManager에서 기본 백업 레이블을 만듭니다. 이러한 SnapManager 매개 변수를 사용하여 기본 백업 레이블을 사용자 지정할 수 있습니다. 백업 레이블을 사용자 지정하려면 override.default.backup.pattern 값이 true 로 설정되어 있는지 확인하십시오. 기본값은 false 입니다.

백업 레이블의 새 패턴을 할당하려면 데이터베이스 이름, 프로필 이름, 범위, 모드 및 호스트 이름과 같은 키워드를 new.default.backup.pattern 에 할당할 수 있습니다. 키워드는 밑줄을 사용하여 구분해야 합니다. 예: new.default.backup.pattern=dbname_profile_hostname_scope_mode.


NOTE: 타임스탬프는 생성된 레이블의 끝에 자동으로 포함됩니다.



 a| 
allow.underscore.in.clone.sid
 a| 
Oracle에서는 Oracle 11gR2의 클론 SID에서 언더스코어를 사용할 수 있습니다. 이 SnapManager 매개 변수를 사용하면 클론 SID 이름에 밑줄을 포함할 수 있습니다. 클론 SID 이름에 밑줄을 포함하려면 allow.underscore.in.clone.sid 값이 true 로 설정되어 있는지 확인하십시오. 기본값은 true 입니다.

Oracle 11gR2 이전 버전의 Oracle을 사용하거나 클론 SID 이름에 밑줄을 포함하지 않으려면 값을 false로 설정합니다.



 a| 
oracle.parameters.with.comma
 a| 
이 매개 변수를 사용하면 쉼표(,)가 있는 모든 Oracle 매개 변수를 값으로 지정할 수 있습니다. 모든 작업을 수행하는 동안 SnapManager는 oracle.parameters.with.comma 를 사용하여 모든 Oracle 매개 변수를 확인하고 값 분할을 건너뜁니다.

예를 들어 nls_numeric_characters= 의 값이 인 경우 oracle.parameters.with.comma=nls_numeric_characters 를 지정합니다. 값으로 쉼표가 있는 여러 개의 Oracle 매개 변수가 있는 경우 oracle.parameters.with.comma 에서 모든 매개 변수를 지정해야 합니다.



 a| 
* 보관 로그.제외
* archedLogs.exclude.fileslike
* db-unique-name>.archivedLogs.exclude.fileslike

 a| 
이러한 매개 변수를 사용하면 데이터베이스가 스냅샷 복사본 지원 스토리지 시스템에 있지 않고 해당 스토리지 시스템에서 SnapManager 작업을 수행하려는 경우 SnapManager에서 프로파일 및 백업에서 아카이브 로그 파일을 제외할 수 있습니다. * 참고: * 를 생성하기 전에 구성 파일에 제외 매개 변수를 포함해야 합니다 프로파일.

이러한 매개 변수에 할당된 값은 최상위 디렉토리이거나 아카이브 로그 파일이 있는 마운트 지점이거나 하위 디렉토리일 수 있습니다. 최상위 디렉토리 또는 마운트 지점이 지정되고 호스트의 프로필에 대해 데이터 보호가 설정된 경우 해당 마운트 지점 또는 디렉토리가 Protection Manager에서 생성된 데이터 세트에 포함되지 않습니다. 호스트에서 제외할 아카이브 로그 파일이 여러 개 있는 경우 쉼표를 사용하여 아카이브 로그 파일 경로를 구분해야 합니다.

아카이브 로그 파일이 프로필에 포함되지 않고 백업되지 않도록 하려면 다음 매개 변수 중 하나를 포함해야 합니다.

* archivedLogs.exclude 모든 프로파일 또는 백업에서 아카이브 로그 파일을 제외하기 위한 정규식을 지정합니다.
+
정규식과 일치하는 아카이브 로그 파일은 모든 프로파일 및 백업에서 제외됩니다.

+
예를 들어 archivedLogs.exclude=/arch/logs/on/local/disk1/. *, /arch/logs/on/local/disk2/. * 를 설정할 수 있습니다. ASM 데이터베이스의 경우 archivedLogs.exclude=\\\+ KHDB_ARCH_DEST/khdb/archivelog/. *, \\+ KHDB_NONARCHTWO/khdb/archivelog/. * 를 설정할 수 있습니다.

* archivedLogs.exclude.fileslike 모든 프로파일 또는 백업에서 아카이브 로그 파일을 제외하기 위한 SQL 식을 지정합니다.
+
SQL 표현식과 일치하는 아카이브 로그 파일은 모든 프로파일 및 백업에서 제외됩니다.

+
예를 들어 archivedLogs.exclude.fileslike=/arch/logs/on/local/disk1/%, /arch/logs/on/local/disk2/%를 설정할 수 있습니다.

* db-unique-name>.archivedLogs.exclude.fileslike 지정된 db-unique-name을 사용하여 데이터베이스에 대해 생성된 백업 또는 프로파일에서 아카이브 로그 파일을 제외하기 위한 SQL 식을 지정합니다.
+
SQL 표현식과 일치하는 아카이브 로그 파일은 프로파일 및 백업에서 제외됩니다.

+
예를 들어 mydb.archivedLogs.exclude.fileslike=/arch/logs/on/local/disk1/%, /arch/logs/on/local/disk2/%를 설정할 수 있습니다.



|===