---
permalink: unix-administration/reference_troubleshooting_known_issues.html 
sidebar: sidebar 
keywords: aware, known, issue, snapmanager, troubleshoot, identify, cluster-mode 
summary: SnapManager를 사용할 때 발생할 수 있는 몇 가지 알려진 문제와 해결 방법을 알고 있어야 합니다. 
---
= 알려진 문제 해결
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapManager를 사용할 때 발생할 수 있는 몇 가지 알려진 문제와 해결 방법을 알고 있어야 합니다.



== SnapManager for Oracle이 클러스터 모드 프로파일을 식별하지 못합니다

SnapManager for Oracle 설치 디렉토리의 cmode_profiles.config 파일에 클러스터 모드 프로파일 이름이 없으면 다음 오류 메시지가 트리거될 수 있습니다.

SnapDrive config set-DFM user_name appliance_name을 사용하여 DFM 서버를 구성하십시오.

또한 Oracle용 SnapManager를 업그레이드하는 동안 /opt/netapp/smo/ * 폴더를 삭제하면 클러스터 모드 프로파일 이름이 인 cmode_profiles.config 파일도 삭제됩니다. 이 문제는 또한 동일한 오류 메시지를 트리거합니다.

* 해결 방법 *

프로필 업데이트: SMO 프로필 업데이트 - 프로필 <profile_name>


NOTE: Oracle용 SnapManager가 /opt/netapp/smo/경로에 설치된 경우 파일 위치는 /opt/netapp/smo/cmode_profile/cmode_profiles.config입니다.



== 서버가 시작되지 않습니다

서버를 시작할 때 다음과 유사한 오류 메시지가 나타날 수 있습니다.

SMO-01104: 명령 호출 오류: SMO-17107: 다음 오류로 인해 포트 8074에서 SnapManager 서버를 시작하지 못했습니다: java.net.BindException: 주소가 이미 사용 중입니다

이는 SnapManager 수신 대기 포트(기본적으로 27214 및 27215)가 현재 다른 응용 프로그램에서 사용되고 있기 때문일 수 있습니다.

이 오류는 SMO_server 명령이 이미 실행 중이지만 SnapManager가 기존 프로세스를 감지하지 못하는 경우에도 발생할 수 있습니다.

* 해결 방법 *

다른 포트를 사용하도록 SnapManager 또는 다른 애플리케이션을 재구성할 수 있습니다.

SnapManager를 재구성하려면 /opt/ntap/smo/properties/smo.config 파일을 편집합니다

다음 값을 할당합니다.

* SMO Server.port = 27214
* SMO 서버.rmiRegistry.port = 27215
* remote.registry.socijdbc.port=27215
+
remote.registry.socijdbc.port는 Server.rmiRegistry.port와 같아야 합니다.



SnapManager 서버를 시작하려면 다음 명령을 입력합니다. smo_server start


NOTE: 서버가 이미 실행 중인 경우 오류 메시지가 표시됩니다.

서버가 이미 실행 중인 경우 다음 단계를 수행하십시오.

. smo_server stop 명령을 입력하여 서버를 중지합니다
. smo_server start 명령을 입력하여 서버를 다시 시작합니다




== 현재 실행 중인 SnapManager 작업을 종료합니다

SnapManager 서버가 중단되어 작업을 성공적으로 실행할 수 없는 경우 SnapManager 및 해당 작업을 종료할 수 있습니다.

* 해결 방법 *

SnapManager는 SnapManager 및 Protection Manager와 모두 호환됩니다. 실행 중인 여러 프로세스를 나열하고 마지막으로 실행 중인 프로세스를 중지하려면 다음 단계를 수행해야 합니다.

. 실행 중인 모든 SnapDrive 프로세스 나열: ps
+
예: ps | grep SnapDrive

. SnapDrive 프로세스 또는 프로세스를 중지합니다. kill <pid>
+
PID는 PS 명령을 사용하여 찾은 프로세스의 목록입니다.

+

NOTE: 모든 SnapDrive 프로세스를 중지하지 마십시오. 실행 중인 마지막 프로세스만 종료할 수 있습니다.

. 작업 중 하나가 보조 스토리지에서 보호된 백업을 복원하는 경우 Protection Manager 콘솔을 열고 다음을 수행합니다.
+
.. 시스템 메뉴에서 * 작업 * 을 선택합니다.
.. Restore * 를 선택합니다.
.. SnapManager 프로파일의 데이터 세트와 일치하는 데이터 세트의 이름을 확인합니다.
.. 마우스 오른쪽 버튼을 클릭하고 * Cancel * (취소 *)을 선택합니다.


. SnapManager 프로세스 나열:
+
.. 루트 사용자로 로그인합니다.
.. PS 명령을 사용하여 프로세스를 나열합니다.
+
예: ps | grep java



. SnapManager 프로세스를 종료합니다. kill <pid>




== 마지막으로 보호된 백업을 삭제하거나 해제할 수 없습니다

보조 스토리지에 있는 프로파일에 대한 첫 번째 백업을 생성하면 SnapManager는 백업에 대한 모든 정보를 Protection Manager로 보냅니다. 이 프로파일과 관련된 후속 백업의 경우 SnapManager는 수정된 정보만 전송합니다. 마지막으로 보호된 백업을 제거하면 SnapManager에서 백업 간의 차이를 확인할 수 없게 되므로 이러한 관계의 기준을 다시 설정할 방법을 찾아야 합니다. 따라서 마지막으로 보호된 백업을 삭제하려고 하면 오류 메시지가 표시됩니다.

* 해결 방법 *

프로파일을 삭제하거나 프로파일 백업만 삭제할 수 있습니다.

프로파일을 삭제하려면 다음 단계를 수행하십시오.

. 프로필의 백업을 삭제합니다.
. 프로필을 업데이트하고 프로필에서 보호 기능을 비활성화합니다.
+
그러면 데이터 세트가 삭제됩니다.

. 마지막으로 보호된 백업을 삭제합니다.
. 프로필을 삭제합니다.


백업만 삭제하려면 다음 단계를 수행하십시오.

. 프로필의 다른 백업 복사본을 만듭니다.
. 백업 복사본을 보조 스토리지로 전송합니다.
. 이전 백업 복사본을 삭제합니다.




== 대상 이름이 다른 대상 이름의 일부인 경우 아카이브 로그 파일 대상 이름을 관리할 수 없습니다

아카이브 로그 백업을 생성하는 동안 사용자가 다른 대상 이름에 속하는 대상을 제외하는 경우 다른 대상 이름도 제외됩니다.

예를 들어, 제외할 수 있는 대상이 /dest, /dest1 및 /dest2라고 가정합니다. 아카이브 로그 파일 백업을 생성하는 동안 명령을 사용하여 /dest를 제외할 경우

[listing]
----
smo backup create -profile almsamp1 -data -online -archivelogs  -exclude-dest /dest
----
, Oracle용 SnapManager는 /dest로 시작하는 모든 대상을 제외합니다.

* 해결 방법 *

* v$archive_dest에서 대상을 구성한 후 경로 구분 기호를 추가합니다. 예를 들어 /dest 를 /dest/ 로 변경합니다.
* 백업을 생성하는 동안 대상을 제외하고 대상을 포함합니다.




== ASM(Automatic Storage Management)에서 멀티플렉싱되고 비 ASM 스토리지가 아닌 제어 파일을 복원하지 못합니다

제어 파일이 ASM 및 비 ASM 스토리지에서 멀티플렉싱되면 백업 작업이 성공한 것입니다. 그러나 성공한 백업에서 제어 파일을 복원하려고 하면 복원 작업이 실패합니다.



== SnapManager 클론 작업이 실패했습니다

SnapManager에서 백업을 클론하면 DataFabric Manager 서버가 볼륨을 검색하지 못하고 다음 오류 메시지를 표시할 수 있습니다.

SMO-13032: 작업을 수행할 수 없음: 클론 생성. 근본 원인:SMO-11007: 스냅샷에서 오류 복제:flow-11019:ExecuteConnectionSteps:SD-00018:/mnt/datafile_clone3:SD-10016에 대한 스토리지를 검색하는 동안 오류가 발생했습니다. SnapDrive 명령 "/usr/sbin/SnapDrive storage show -fs/mnt/datafile_clone3":0002-719 경고: vols.vx001S1에서 사용자 vm/vx00읽기 파일 시스템 서버에 대한 Oracle 읽기 파일 시스템 액세스를 확인할 수 없습니다

이유: 잘못된 리소스가 지정되었습니다. Operations Manager 서버 10.x.x.x에서 ID를 찾을 수 없습니다

이 문제는 스토리지 시스템에 많은 수의 볼륨이 있는 경우에 발생합니다.

* 해결 방법 *

다음 중 하나를 수행해야 합니다.

* Data Fabric Manager 서버에서 DFM 호스트 검색 storage_system을 실행합니다.
+
또한 셸 스크립트 파일에 명령을 추가하고 DataFabric Manager 서버에서 작업을 예약하여 스크립트를 자주 실행할 수도 있습니다.

* SnapDrive.conf 파일에서 DFM-RBAC-RETRIES 값을 늘립니다.
+
SnapDrive는 기본 새로 고침 간격 값과 기본 재시도 횟수를 사용합니다. DFM-RBAC-RETRY-SLEEP-Seconds의 기본값은 15초이고 DFM-RBAC-RETRIES는 12회 반복 시도입니다.

+

NOTE: Operations Manager 새로 고침 간격은 스토리지 시스템의 수, 스토리지 시스템의 스토리지 객체 수 및 DataFabric Manager 서버의 로드에 따라 달라집니다.

+
권장사항으로서 다음을 수행하십시오.

+
.. DataFabric Manager 서버에서 데이터 세트와 연결된 모든 2차 스토리지 시스템에 대해 다음 명령을 수동으로 실행합니다. DFM host Discover storage_system
.. 호스트 검색 작업을 수행하는 데 걸리는 시간을 2배로 늘리고 이 값을 DFM-RBAC-RETRY-SLEEP에 할당합니다.
+
예를 들어, 작업 시간이 11초가 걸리는 경우 DFM-RBAC-RETRY-SLEEP-Seconds 값을 22(11 * 2)로 설정할 수 있습니다.







== 저장소 데이터베이스 크기는 백업 수가 아닌 시간에 따라 증가합니다

SnapManager 작업은 저장소 데이터베이스 테이블의 스키마 내에서 데이터를 삽입하거나 삭제하므로 저장소 데이터베이스 크기가 시간이 지나면서 증가하므로 인덱스 공간 사용량이 높아집니다.

* 해결 방법 *

리포지토리 스키마에서 사용되는 공간을 제어하려면 Oracle 지침에 따라 인덱스를 모니터링하고 재구성해야 합니다.



== 리포지토리 데이터베이스가 다운된 경우 SnapManager GUI에 액세스할 수 없으며 SnapManager 작업이 실패합니다

SnapManager 작업이 실패하고 리포지토리 데이터베이스가 다운된 경우 GUI에 액세스할 수 없습니다.

다음 표에는 수행할 수 있는 여러 작업과 해당 예외 사항이 나열되어 있습니다.

|===


| 운영 | 예외 


 a| 
닫힌 리포지토리를 엽니다
 a| 
sm_gui.log에 다음 오류 메시지가 기록됩니다. [WARN]: smo-01106: 리포지토리를 쿼리하는 동안 오류가 발생했습니다. 종료된 연결 java.sql.SqlException: 종료된 연결.



 a| 
F5 키를 눌러 열려 있는 리포지토리를 새로 고칩니다
 a| 
리포지토리 예외는 GUI에 표시되며 sm_gui.log 파일에 NullPointerException도 기록합니다.



 a| 
호스트 서버를 새로 고치는 중입니다
 a| 
NullPointerException 은 sumo_gui.log 파일에 기록됩니다.



 a| 
새 프로파일 만들기
 a| 
프로필 구성 창에 NullPointerException 이 표시됩니다.



 a| 
프로파일을 새로 고치는 중입니다
 a| 
sm_gui.log에 다음 SQL 예외가 기록됩니다. [WARN]: smo-01106: 리포지토리를 쿼리하는 동안 오류가 발생했습니다. 닫힌 연결.



 a| 
백업에 액세스하는 중입니다
 a| 
sm_gui.log에 다음 오류 메시지가 기록됩니다. lazzily 수집 초기화 실패.



 a| 
클론 속성 보기
 a| 
sm_gui.log 및 sumo_GUI.log에 다음 오류 메시지가 기록됩니다. 수집을 lazily 초기화하지 못했습니다.

|===
* 해결 방법 *

GUI에 액세스하거나 SnapManager 작업을 수행하려는 경우 저장소 데이터베이스가 실행 중인지 확인해야 합니다.



== 복제된 데이터베이스에 대한 임시 파일을 생성할 수 없습니다

타겟 데이터베이스의 임시 테이블스페이스 파일이 데이터 파일의 마운트 지점이 아닌 마운트 지점에 배치된 경우 클론 생성 작업은 성공하지만 SnapManager는 클론 데이터베이스의 임시 파일을 생성하지 못합니다.

* 해결 방법 *

다음 중 하나를 수행해야 합니다.

* 임시 파일이 데이터 파일의 마운트 지점과 동일한 위치에 배치되도록 타겟 데이터베이스가 배치되었는지 확인합니다.
* 복제된 데이터베이스에 임시 파일을 수동으로 만들거나 추가합니다.




== NFSv3에서 NFSv4로 프로토콜을 마이그레이션할 수 없습니다

SnapDrive.conf 파일에서 enable-migrate-nfs-version 매개 변수를 설정하여 NFSv3에서 NFSv4로 프로토콜을 마이그레이션할 수 있습니다. 마이그레이션 중에 SnapDrive는 RW, largefiles, nosuid 등과 같은 마운트 지점 옵션과 관계없이 프로토콜 버전만 고려합니다.

하지만 NFSv3을 사용하여 생성한 백업을 복원하면 프로토콜을 NFSv4로 마이그레이션한 후 다음 작업이 수행됩니다.

* 스토리지 레벨에서 NFSv3과 NFSv4가 설정된 경우 복구 작업은 성공하지만 백업 중에 사용할 수 있는 마운트 지점 옵션으로 마운트됩니다.
* 스토리지 레벨에서 NFSv4만 설정된 경우 복구 작업이 성공하고 프로토콜 버전(NFSv4)만 유지됩니다.
+
그러나 RW, largefiles, nosuid 등과 같은 다른 마운트 지점 옵션은 유지되지 않습니다.



* 해결 방법 *

데이터베이스를 수동으로 종료하고 데이터베이스 마운트 지점을 마운트 해제하고 복구 전에 사용 가능한 옵션을 사용하여 마운트해야 합니다.



== Data Guard 대기 데이터베이스 백업 실패

보관 로그 위치가 기본 데이터베이스의 서비스 이름으로 구성된 경우 Data Guard 대기 데이터베이스 백업 작업이 실패합니다.

* 해결 방법 *

GUI에서 기본 데이터베이스의 서비스 이름에 해당하는 * 외부 아카이브 로그 위치 지정 * 의 선택을 해제해야 합니다.
