---
permalink: unix-administration/task_cloning_databases_from_backups.html 
sidebar: sidebar 
keywords: clone, database, backup, using, clone, create, command, sid, snapmanager 
summary: clone create 명령을 사용하여 백업에서 데이터베이스를 복제할 수 있습니다. 
---
= 백업에서 데이터베이스 클론 생성
:icons: font
:imagesdir: ../media/


[role="lead"]
clone create 명령을 사용하여 백업에서 데이터베이스를 복제할 수 있습니다.

먼저 데이터베이스에 대한 클론 지정 파일을 생성해야 합니다. SnapManager는 이 사양 파일의 정보를 기반으로 클론을 생성합니다.

클론에 새 Oracle SID(시스템 식별자)를 제공해야 합니다. 동일한 호스트에서 동일한 SID로 두 데이터베이스를 동시에 실행할 수 없습니다. 동일한 SID를 사용하는 다른 호스트에 클론을 생성할 수 있습니다. 클론의 고유한 이름을 지정하려면 -label 을 사용합니다. 이 옵션을 사용하지 않으면 SnapManager에서 SID, 날짜 및 시간을 포함하는 클론의 고유 이름을 생성합니다.

데이터베이스를 복제한 후 클라이언트 컴퓨터의 tnsnames.ora 파일을 복제된 새 데이터베이스 연결 정보로 업데이트할 수 있습니다. tnsnames.ora 파일은 전체 데이터베이스 정보를 지정하지 않고 Oracle 인스턴스에 연결하는 데 사용됩니다. SnapManager는 tnsnames.ora 파일을 업데이트하지 않습니다.

include-with-online-backups로 생성된 프로파일을 사용하는 경우 SnapManager는 항상 아카이브 로그 파일을 포함한 백업을 생성합니다. SnapManager에서는 전체 데이터베이스 백업만 복제할 수 있습니다.

SnapManager(3.2 이상)를 사용하면 데이터 파일과 아카이브 로그 파일이 포함된 백업을 복제할 수 있습니다.

아카이브 로그를 외부 위치에서 사용할 수 있는 경우 클론 생성 중에 외부 위치를 지정하여 복제된 데이터베이스를 정합성 보장 상태로 복구할 수 있습니다. Oracle에서 외부 위치에 액세스할 수 있는지 확인해야 합니다. 아카이브 로그 전용 백업의 클론 생성은 지원되지 않습니다.

아카이브 로그 백업이 온라인 부분 백업과 함께 생성되지만 이 백업을 사용하여 데이터베이스 클론을 생성할 수는 없습니다.

독립 실행형 데이터베이스에만 외부 아카이브 로그 파일 위치에서 데이터베이스 백업을 복제할 수 있습니다.

복구 실패 때문에 외부 아카이브 로그 파일 위치를 사용하여 RAC(Real Application Clusters) 데이터베이스의 온라인 데이터베이스 백업 복제가 실패합니다. 이는 Oracle 데이터베이스가 데이터베이스 백업 클론 생성 중에 외부 아카이브 로그 위치에서 복구를 위해 아카이브 로그 파일을 찾고 적용하는 데 실패하기 때문입니다.

덤프 옵션을 선택적 매개 변수로 지정하여 성공한 클론 생성 작업 또는 실패한 클론 생성 작업 후 덤프 파일을 수집할 수 있습니다.

* 아카이브 로그 백업 없이 데이터 파일 백업 클로닝 *

데이터 파일 백업에 아카이브 로그 백업이 포함되지 않은 경우 SnapManager for Oracle은 백업 중에 기록된 SCN(시스템 변경 번호)을 기반으로 데이터베이스를 복제합니다. 클론된 데이터베이스를 복구할 수 없는 경우 SnapManager for Oracle이 계속해서 데이터베이스를 복제하고 마지막으로 클론을 생성하더라도 스레드 <number> 및 복구 완료에 필요한 변경 <scn> 요청 메시지가 표시됩니다.

아카이브 로그 백업을 포함하지 않고 데이터 파일 백업을 사용하여 클론을 생성할 경우 SnapManager는 백업 중에 기록된 마지막 아카이브 로그 SCN이 될 때까지 복제된 데이터베이스를 복구합니다.

. 클론 사양 파일을 생성합니다.
. 클론을 생성하려면 다음 명령을 입력합니다. smo clone create -backup -labelbackup_name -newsidnew_sid -labelclone_label -profileprofile_name -clonespecall_path_to_clonespecfile [-taskspec] [-recover-from-location] path1 [, <path2>...] [-dump]


* 관련 정보 *

xref:task_cloning_databases_in_the_current_state.adoc[현재 상태의 데이터베이스 클론 생성]

xref:concept_considerations_for_cloning_a_database_to_an_alternate_host.adoc[데이터베이스를 대체 호스트에 클론 생성할 때의 고려 사항]

xref:task_creating_clone_specifications.adoc[클론 사양 생성 중]

xref:reference_the_smosmsapclone_create_command.adoc[SMO 복제 create 명령]

xref:task_creating_pretask_post_task_and_policy_scripts.adoc[사전 작업, 사후 작업 및 정책 스크립트 생성]

xref:concept_variables_available_in_the_task_scripts_for_clone_operation.adoc[클론 작업을 위해 작업 스크립트에서 사용할 수 있는 변수입니다]

xref:task_creating_task_scripts.adoc[작업 스크립트 작성]

xref:task_storing_the_task_scripts.adoc[작업 스크립트 저장]
