---
permalink: unix-administration/task_updating_storage_system_name_associated_with_a_profile.html 
sidebar: sidebar 
keywords: snapmanager, 3.3, ability, update, host, name, ip, address, storage, system, associate, profile, updating, smo 
summary: SnapManager 3.3 이상에서는 프로필과 연결된 스토리지 시스템의 호스트 이름 또는 IP 주소를 업데이트할 수 있습니다. 
---
= 프로파일과 연결된 스토리지 시스템 이름을 업데이트하는 중입니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapManager 3.3 이상에서는 프로필과 연결된 스토리지 시스템의 호스트 이름 또는 IP 주소를 업데이트할 수 있습니다.

다음 사항을 확인해야 합니다.

* 프로필에 백업이 하나 이상 있습니다.
+
프로필에 백업이 없는 경우 해당 프로필의 스토리지 시스템 이름을 업데이트할 필요가 없습니다.

* 프로파일에 대해 실행 중인 작업이 없습니다.


SnapManager CLI(Command-Line Interface)를 사용하여 스토리지 시스템 이름 또는 IP 주소를 업데이트할 수 있습니다. 스토리지 시스템 이름을 업데이트하는 동안 저장소 데이터베이스에 저장된 메타데이터만 업데이트됩니다. 스토리지 시스템 이름의 이름을 바꾼 후 모든 SnapManager 작업을 이전 버전으로 수행할 수 있습니다.


NOTE: SnapManager GUI(그래픽 사용자 인터페이스)를 사용하여 스토리지 시스템 이름을 변경할 수 없습니다.

새 스토리지 시스템에서 스냅샷 복사본을 사용할 수 있는지 확인해야 합니다. SnapManager은 스토리지 시스템에 스냅샷 복사본이 있는지 여부를 확인하지 않습니다.

그러나 스토리지 시스템 이름을 변경한 후 호스트의 롤링 업그레이드 및 롤백을 수행하는 동안 다음 사항을 기억해야 합니다.

* 스토리지 시스템 이름의 이름을 바꾼 후 호스트의 롤링 업그레이드를 수행하는 경우 새 스토리지 시스템 이름으로 프로필을 업데이트해야 합니다.
+
스토리지 시스템 이름을 변경하는 데 SnapDrive 명령을 사용하는 방법에 대한 자세한 내용은 _스토리지 시스템 이름 문제 해결_을 참조하십시오.

* 스토리지 시스템의 이름을 바꾼 후 호스트를 롤백하는 경우 SnapManager 작업을 수행하기 위해 이전 스토리지 시스템의 프로파일, 백업 및 클론을 사용할 수 있도록 스토리지 시스템 이름을 이전 스토리지 시스템 이름으로 다시 변경해야 합니다.



NOTE: SnapDrive가 스토리지 시스템을 식별할 수 없고 오류 메시지가 표시되는 경우 스토리지 시스템의 이전 호스트 이름 및 이후 호스트 이름을 사용하여 ipmigrate 명령을 입력할 수 있습니다. 스토리지 시스템 이름 문제에 대한 자세한 내용은 _ 스토리지 시스템 이름 문제 해결 _ 을(를) 참조하십시오.

. 'smo storage rename -profileprofile -oldnameold_storage_name -newnamenew_storage_name [quiet | -verbose]' 명령을 입력합니다
+
|===
| 원하는 작업 | 그러면... 


 a| 
프로파일과 연결된 스토리지 시스템 이름을 업데이트합니다
 a| 
profile 옵션을 지정합니다.



 a| 
프로파일과 연결된 스토리지 시스템 이름 또는 IP 주소를 업데이트합니다
 a| 
다음 옵션 및 변수를 지정합니다.

** -oldnameold_storage_name 은 스토리지 시스템의 호스트 이름 또는 IP 주소입니다.
** newnamenew_storage_name은 스토리지 시스템의 호스트 이름 또는 IP 주소입니다.


|===


다음 예에서는 업데이트되는 스토리지 시스템 이름을 보여 줍니다.

[listing]
----
smo storage rename -profile mjullian -oldname lech -newname hudson -verbose
----
* 관련 정보 *

xref:reference_troubleshooting_storage_system_renaming_issue.adoc[스토리지 시스템의 이름 바꾸기 문제 해결]
