---
permalink: unix-administration/task_previewing_backup_restore_information.html 
sidebar: sidebar 
keywords: preview, information, backup, restore, process, occurs, eligibility, storage-side, fast, file 
summary: 백업 복원 프로세스가 발생하기 전에 백업 복원 프로세스에 대한 정보를 미리 보고 SnapManager for Oracle이 백업에서 찾은 복원 자격에 대한 정보를 확인할 수 있습니다. SnapManager는 백업 데이터를 분석하여 복원 프로세스를 성공적으로 완료할 수 있는지 여부를 결정합니다. 
---
= 백업 복원 정보를 미리 보는 중입니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
백업 복원 프로세스가 발생하기 전에 백업 복원 프로세스에 대한 정보를 미리 보고 SnapManager for Oracle이 백업에서 찾은 복원 자격에 대한 정보를 확인할 수 있습니다. SnapManager는 백업 데이터를 분석하여 복원 프로세스를 성공적으로 완료할 수 있는지 여부를 결정합니다.

복원 미리 보기에는 다음 정보가 제공됩니다.

* 각 파일을 복구하는 데 사용할 수 있는 복구 메커니즘(빠른 복구, 스토리지 측 파일 시스템 복구, 스토리지 측 파일 복구 또는 호스트 측 파일 복사 복구)은 무엇입니까?
* verbose 옵션을 지정할 때 각 파일을 복원하는 데 보다 효율적인 메커니즘을 사용하지 않은 이유는 무엇입니까?


백업 복원 명령에서 -preview 옵션을 지정하면 SnapManager는 아무 것도 복원하지 않고 복원할 파일이 나열되고 복원 방법을 표시합니다.


NOTE: 모든 유형의 복원 메커니즘을 미리 볼 수 있습니다. 미리보기에 최대 20개 파일에 대한 정보가 표시됩니다.

. smo backup restore-profileprofile_name-labellabel-complete-preview-verbose 명령을 입력합니다
+
예를 들어 다음을 입력합니다.

+
[listing]
----
smo backup restore -profile targetdb1_prof1
      -label full_bkup_sales_nov_08  -complete -preview -verbose
----
+
다음 예에서는 호스트 측 파일 복사 복원 프로세스를 사용하여 복구되는 일부 파일을 보여 주고, 빠른 복원 옵션을 사용하여 일부 파일을 복원할 수 없는 이유에 대해서도 설명합니다. verbose 옵션을 지정하면 SnapManager는 빠른 복원 프로세스를 통해 각 파일을 복원할 수 없는 이유를 설명하는 미리 보기 섹션과 분석 섹션을 표시합니다.

+
[listing]
----
PREVIEW:
The following files will be restored via host side file copy restore:
+DG2/sid/datafile10.dbf
+DG2/sid/datafile11.dbf

ANALYSIS:
The following reasons prevent certain files from being restored via fast restore:
Reasons:
 Newer snapshots of /vol/volume2 have volume clones: SNAP_1
*Newer backups will be freed: nightly2, nightly3
Files to Restore:
/mnt/systemB/volume2/system.dbf
/mnt/systemB/volume2/users.dbf
/mnt/systemB/volume2/sysaux.dbf
/mnt/systemB/volume2/datafile04.dbf
/mnt/systemB/volume2/datafile05.dbf

The following reasons prevent certain files from being restored via fast restore:
Reasons:
* Newer snapshots of /vol/adm_disks will be lost: ADM_SNAP_5
* Luns present which were created after snapshot SNAP_0 was created: /vol/adm_disks/disk5.lun
* Files not part of the restore scope will be reverted in file system: +DG2

Files Not in Restore Scope: +DG2/someothersid/data01.dbf
+DG2/someothersid/data02.dbf
Files to Restore:
+DG2/sid/datafile08.dbf +DG2/sid/datafile09.dbf
+DG2/sid/datafile10.dbf +DG2/sid/datafile11.dbf

* Reasons denoted with an asterisk (*) are overridable.
----
. 다른 복원 프로세스를 사용할 수 없는 이유를 검토합니다.
. 재정의 가능한 이유만 표시되는 경우 -preview 옵션 없이 복원 작업을 시작합니다.
+
여전히 비필수 검사를 재정의할 수 있습니다.


