---
permalink: unix-administration/task_creating_clone_specifications.html 
sidebar: sidebar 
keywords: snapmanager, oracle, clone, specification, xml, file, mapping, option, parameter, creating 
summary: SnapManager for Oracle은 클론 작업에 사용할 매핑, 옵션 및 매개 변수가 포함된 클론 사양 XML 파일을 사용합니다. SnapManager는 이 정보를 사용하여 클론 파일을 저장할 위치와 진단 정보, 제어 파일, 매개 변수 등을 처리하는 방법을 결정합니다. 
---
= 클론 사양 생성 중
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapManager for Oracle은 클론 작업에 사용할 매핑, 옵션 및 매개 변수가 포함된 클론 사양 XML 파일을 사용합니다. SnapManager는 이 정보를 사용하여 클론 파일을 저장할 위치와 진단 정보, 제어 파일, 매개 변수 등을 처리하는 방법을 결정합니다.

SnapManager 그래픽 사용자 인터페이스(GUI), 명령줄 인터페이스(CLI) 또는 텍스트 편집기를 사용하여 클론 사양 파일을 생성할 수 있습니다.

텍스트 편집기를 사용하여 클론 사양 파일을 생성할 때 .xml 파일로 저장해야 합니다. 이 XML 파일을 다른 클론 작업에 사용할 수 있습니다.

클론 사양 템플릿을 생성한 다음 사용자 지정할 수도 있습니다. SMO 복제 템플릿 명령을 사용하거나 GUI에서 복제 마법사를 사용할 수 있습니다.

SnapManager for Oracle은 생성하는 모든 클론 사양 템플릿에 버전 문자열을 추가합니다. Oracle용 SnapManager는 버전 문자열이 없는 모든 클론 사양 파일의 최신 버전을 가정합니다.

원격 클론 생성을 수행하려면 클론 사양 파일에서 데이터 파일의 기본 위치, 재실행 로그 파일 및 제어 파일을 변경하지 마십시오. 기본 위치를 변경하면 SnapManager에서 클론을 생성하지 못하거나 스냅샷 기능을 지원하지 않는 데이터베이스에 클론을 생성하지 못합니다. 따라서 프로파일 자동 생성이 실패합니다.


NOTE: 마운트 지점 및 ASM 디스크 그룹 정보는 GUI에서 편집할 수 있지만 파일 위치는 변경하지 않고 파일 이름만 변경할 수 있습니다.

동일하거나 다른 매개 변수 및 값 조합으로 작업을 여러 번 실행할 수 있습니다.

. 다음 예제와 같이 텍스트 파일을 열고 텍스트를 입력합니다.
+
[listing]
----
<clone-specification xmlns="http://www.example.com>
     <storage-specification/>
     <database-specification/>
 </clone-specification>
----
. 스토리지 사양 구성 요소에서 데이터 파일의 마운트 지점을 입력합니다.
+
스토리지 사양에는 데이터 파일 마운트 지점 및 원시 디바이스와 같이 클론에 대해 생성된 새 스토리지의 위치가 나열됩니다. 이러한 항목은 소스에서 대상으로 매핑되어야 합니다.

+
다음 예에서는 클론 사양에 사용되는 데이터 파일 마운트 지점 구문을 보여 줍니다.

+
[listing]
----
<mountpoint>
     <source>/mnt/path/source_data file_mountpoint</source>
     <destination>/mnt/path/target_data file_mountpoint</destination>
</mountpoint>
----
. 선택 사항: 소스에 원시 디바이스가 있는 경우 소스의 원시 디바이스에 대한 경로를 지정한 다음 대상에 대한 대상 자동 생성=" true" 를 지정해야 합니다.
+
이전 버전의 Oracle용 SnapManager의 클론 매핑 파일과 달리, 대상에서 원시 디바이스의 위치를 지정할 수 없습니다. SnapManager for Oracle은 복제된 원시 디바이스에 사용할 수 있는 다음 디바이스 이름을 선택합니다.

+
다음 예에서는 클론 사양에 사용하는 원시 디바이스 구문을 표시합니다.

+
[listing]
----
<raw-device>
     <source>/dev/raw/raw1</source>
     <destination auto-generate="true"/>
</raw-device>
----
. 데이터베이스 사양 구성 요소에서 제어 파일 정보를 클론에 대해 생성하려는 제어 파일 목록으로 식별합니다.
+
데이터베이스 사양에서는 제어 파일, 재실행 로그, 아카이브 로그, Oracle 매개 변수 등과 같은 클론의 데이터베이스 옵션을 지정합니다.

+
다음 예제에서는 클론 사양에 사용하는 제어 파일 구문을 보여 줍니다.

+
[listing]
----
<controlfiles>
     <file>/mnt/path/clonename/control/control01.ctl</file>
     <file>/mnt/path/clonename/control/control02.ctl</file>
</controlfiles>
----
. 클론의 redo 로그 구조를 지정합니다.
+
다음 예에서는 클론 생성을 위한 redo 로그 디렉토리 구조를 표시합니다.

+
[listing]
----
<redologs>
     <redogroup>
          <file>/mnt/path/clonename/redo/redo01.log</file>
          <number>1</number>
          <size unit="M">100</size>
     </redogroup>
     <redogroup>
         <file>/mnt/path/clonename/redo/redo02.log</file>
         <number>2</number>
         <size unit="M">100</size>
     </redogroup>
</redologs>
----
. 복제된 데이터베이스의 다른 값으로 설정해야 하는 Oracle 매개 변수를 지정합니다. Oracle 10을 사용하는 경우 다음 매개 변수를 지정해야 합니다.
+
** 백그라운드 덤프
** 코어 덤프
** 사용자 덤프
** (선택 사항) 아카이브 로그
+

NOTE: 매개 변수 값이 올바르게 설정되지 않으면 클론 작업이 중지되고 오류 메시지가 표시됩니다.



+
아카이브 로그가 저장되는 위치를 지정하지 않으면 SnapManager가 해당 클론을 noarchivelog 모드로 생성합니다. SnapManager는 이 매개 변수 정보를 클론의 init.ora 파일에 복사합니다.

+
+ 다음 예제에서는 클론 사양에 사용하는 매개 변수 구문을 표시합니다.

+
를 누릅니다

+
[listing]
----
<parameters>
     <parameter>
          <name>log_archive_dest_1</name>
          <value>LOCATION=/mnt/path/clonename/archive</value>
     </parameter>
</parameters>
----
+
+ 매개 변수 요소 내의 기본 요소를 사용하여 기본값을 사용할 수 있습니다. 다음 예제에서는 기본 요소가 지정되어 있으므로 OS_AUTHENTICATION_PREFIX 매개 변수가 기본값을 사용합니다.

+
를 누릅니다

+
[listing]
----
<parameters>
     <parameter>
          <name>os_authent_prefix</name>
          <default></default>
     </parameter>
</parameters>
----
+
+ 빈 요소를 사용하여 매개 변수의 값으로 빈 문자열을 지정할 수 있습니다. 다음 예에서는 OS_AUTHENTICATION_PREFIX가 빈 문자열로 설정됩니다.

+
를 누릅니다

+
[listing]
----
<parameters>
     <parameter>
          <name>os_authent_prefix</name>
          <value></value>
     </parameter>
</parameters>
----
+
참고: 요소를 지정하지 않으면 소스 데이터베이스의 init.ora 파일에서 매개 변수에 값을 사용할 수 있습니다.

+
+ 매개 변수에 여러 값이 있는 경우 쉼표로 구분된 매개 변수 값을 제공할 수 있습니다. 예를 들어, 데이터 파일을 한 위치에서 다른 위치로 이동하려는 경우 db_file_name_convert 매개 변수를 사용하여 다음 예제와 같이 쉼표로 구분된 데이터 파일 경로를 지정할 수 있습니다.

+
를 누릅니다

+
[listing]
----
<parameters>
     <parameter>
          <name>db_file_name_convert</name>
          <value>>/mnt/path/clonename/data file1,/mnt/path/clonename/data file2</value>
     </parameter>
</parameters>
----
+
+ 로그 파일을 한 위치에서 다른 위치로 이동하려면 다음 예제와 같이 log_file_name_convert 매개 변수를 사용하여 로그 파일 경로를 쉼표로 구분하여 지정할 수 있습니다.

+
를 누릅니다

+
[listing]
----
<parameters>
     <parameter>
          <name>log_file_name_convert</name>
          <value>>/mnt/path/clonename/archivle1,/mnt/path/clonename/archivle2</value>
     </parameter>
</parameters>
----
. 선택 사항: 클론이 온라인 상태일 때 실행할 임의 SQL 문을 지정합니다.
+
SQL 문을 사용하여 복제된 데이터베이스에서 임시 파일을 다시 만드는 등의 작업을 수행할 수 있습니다.

+

NOTE: SQL 문 끝에 세미콜론이 포함되지 않도록 해야 합니다.

+
다음은 클론 작업의 일부로 실행하는 샘플 SQL 문입니다.

+
[listing]
----
<sql-statements>
   <sql-statement>
     ALTER TABLESPACE TEMP ADD
     TEMPFILE '/mnt/path/clonename/temp_user01.dbf'
     SIZE 41943040 REUSE AUTOEXTEND ON NEXT 655360
     MAXSIZE 32767M
   </sql-statement>
</sql-statements>
----




== 클론 사양 예

다음 예에서는 스토리지 및 데이터베이스 사양 구성 요소를 비롯한 클론 사양 구조를 보여 줍니다.

[listing]
----
<clone-specification xmlns="http://www.example.com>

   <storage-specification>
     <storage-mapping>
        <mountpoint>
          <source>/mnt/path/source_mountpoint</source>
          <destination>/mnt/path/target_mountpoint</destination>
        </mountpoint>
        <raw-device>
          <source>/dev/raw/raw1</source>
          <destination auto-generate="true"/>
        </raw-device>
        <raw-device>
          <source>/dev/raw/raw2</source>
          <destination auto-generate="true"/>
        </raw-device>
     </storage-mapping>
   </storage-specification>

   <database-specification>
     <controlfiles>
       <file>/mnt/path/clonename/control/control01.ctl</file>
       <file>/mnt/path/clonename/control/control02.ctl</file>
     </controlfiles>
     <redologs>
         <redogroup>
           <file>/mnt/path/clonename/redo/redo01.log</file>
           <number>1</number>
           <size unit="M">100</size>
        </redogroup>
        <redogroup>
           <file>/mnt/path/clonename/redo/redo02.log</file>
           <number>2</number>
           <size unit="M">100</size>
        </redogroup>
    </redologs>
    <parameters>
      <parameter>
        <name>log_archive_dest_1</name>
        <value>LOCATION=/mnt/path/clonename/archive</value>
      </parameter>
      <parameter>
        <name>background_dump_dest</name>
        <value>/mnt/path/clonename/admin/bdump</value>
      </parameter>
      <parameter>
        <name>core_dump_dest</name>
        <value>/mnt/path/clonename/admin/cdump</value>
      </parameter>
      <parameter>
        <name>user_dump_dest</name>
        <value>/mnt/path/clonename/admin/udump</value>
      </parameter>
    </parameters>
   </database-specification>
</clone-specification>
----
* 관련 정보 *

xref:task_cloning_databases_and_using_custom_plugin_scripts.adoc[데이터베이스 클론 생성 및 맞춤형 플러그인 스크립트 사용]

xref:task_cloning_databases_from_backups.adoc[백업에서 데이터베이스 클론 생성]

xref:task_cloning_databases_in_the_current_state.adoc[현재 상태의 데이터베이스 클론 생성]

xref:concept_considerations_for_cloning_a_database_to_an_alternate_host.adoc[데이터베이스를 대체 호스트에 클론 생성할 때의 고려 사항]
