---
permalink: unix-installation-cmode/task_creating_an_oracle_user_for_the_target_database.html 
sidebar: sidebar 
keywords: oracle, database, user, require, snapmanager, operation, sysdba 
summary: Oracle 데이터베이스 사용자는 데이터베이스에 로그인하고 SnapManager 작업을 수행해야 합니다. 대상 데이터베이스에 대한 sysdba 권한을 가진 사용자가 없는 경우 sysdba 권한으로 이 사용자를 생성해야 합니다. 
---
= 대상 데이터베이스에 대한 Oracle 데이터베이스 사용자를 생성합니다
:icons: font
:imagesdir: ../media/


[role="lead"]
Oracle 데이터베이스 사용자는 데이터베이스에 로그인하고 SnapManager 작업을 수행해야 합니다. 대상 데이터베이스에 대해 _sysdba_권한을 가진 사용자가 없는 경우 _sysdba_권한으로 이 사용자를 생성해야 합니다.

SnapManager는 타겟 데이터베이스에 대해 존재하는 _sysdba_권한으로 모든 Oracle 사용자를 사용할 수 있습니다. 예를 들어, SnapManager는 default_sys_user를 사용할 수 있습니다. 그러나 사용자가 있더라도 타겟 데이터베이스에 대한 새 사용자를 생성하고 _sysdba_권한을 할당할 수 있습니다.

또한 OS(운영 체제)를 통해 Oracle 데이터베이스가 OS에서 유지 관리하는 자격 증명을 사용하여 사용자가 데이터베이스에 로그인하고 SnapManager 작업을 수행할 수 있도록 인증하는 OS 인증 방법을 사용할 수도 있습니다. OS에서 인증된 경우 사용자 이름 또는 암호를 지정하지 않고 Oracle 데이터베이스에 연결할 수 있습니다.

. SQL * Plus에 로그인합니다. sqlplus '/as sysdba'
. 관리자 암호를 사용하여 새 사용자 생성: create useruser_name identified by admin_password;
+
user_name 은 만들고 있는 사용자의 이름이고 admin_password 는 사용자에게 할당할 암호입니다.

. sysdba 권한을 새 Oracle 사용자에게 할당합니다. 사용자_이름에 sysdba를 부여합니다.

