---
permalink: unix-installation-7mode/reference_product_overview.html 
sidebar: sidebar 
keywords: automate, simplifies, complex, manual, time-consuming, process, associate, backup, recover, cloning, oracle, database, snapvault, data, ontap, technology 
summary: Oracle 데이터베이스의 백업, 복구 및 클론 복제와 관련된 복잡하고 시간이 많이 소요되는 수동 프로세스를 자동화 및 단순화합니다. SnapManager with Data ONTAP SnapMirror 기술을 사용하여 다른 볼륨에 백업 복사본을 만들고 Data ONTAP SnapVault 기술을 사용하여 백업을 디스크에 효율적으로 아카이브할 수 있습니다. 
---
= 제품 개요
:icons: font
:imagesdir: ../media/


[role="lead"]
Oracle 데이터베이스의 백업, 복구 및 클론 복제와 관련된 복잡하고 시간이 많이 소요되는 수동 프로세스를 자동화 및 단순화합니다. SnapManager with Data ONTAP SnapMirror 기술을 사용하여 다른 볼륨에 백업 복사본을 만들고 Data ONTAP SnapVault 기술을 사용하여 백업을 디스크에 효율적으로 아카이브할 수 있습니다.

SnapManager는 Oracle RAC(Real Application Clusters), ASM(Automatic Storage Management) 및 FC, iSCSI 및 NFS 프로토콜 간 Direct NFS와 같은 기본 Oracle 기술과 통합됩니다. 필요한 경우 SnapManager를 사용하여 생성한 백업을 Oracle RMAN(Recovery Manager)으로 카탈로그로 작성하여 백업 정보를 보존할 수 있습니다. 이러한 백업은 나중에 블록 레벨 복구 또는 테이블스페이스 시점 복구 작업에서 사용할 수 있습니다.



== SnapManager 하이라이트

SnapManager는 UNIX 호스트 및 백 엔드에서 NetApp Snapshot, SnapRestore 및 FlexClone 기술과 Oracle 데이터베이스와의 원활한 통합을 지원합니다 관리 기능을 위한 CLI(명령줄 인터페이스)뿐만 아니라 사용하기 쉬운 UI(사용자 인터페이스)도 제공합니다.

SnapManager를 사용하면 다음과 같은 데이터베이스 작업을 수행하고 데이터를 효율적으로 관리할 수 있습니다.

* 운영 또는 2차 스토리지에서 공간 효율적인 백업 생성
+
SnapManager를 사용하면 데이터 파일과 아카이브 로그 파일을 개별적으로 백업할 수 있습니다.

* 백업 예약
* 파일 기반 또는 볼륨 기반 복원 작업을 사용하여 전체 또는 부분 데이터베이스 복원
* 백업에서 아카이브 로그 파일을 검색, 마운트 및 적용하여 데이터베이스 복구
* 아카이브 로그의 백업만 생성할 때 아카이브 로그 대상에서 아카이브 로그 파일 잘라내기
* 고유한 아카이브 로그 파일이 포함된 백업만 보존하여 최소 수의 아카이브 로그 백업을 자동으로 유지합니다
* 작업 세부 정보 추적 및 보고서 생성
* 백업이 유효한 블록 형식이고 백업된 파일이 손상되지 않았는지 확인하기 위해 백업을 확인하는 중입니다
* 데이터베이스 프로파일에 대해 수행된 작업 기록을 유지 관리합니다
+
프로파일에는 SnapManager에서 관리할 데이터베이스에 대한 정보가 들어 있습니다.

* 2차 및 3차 스토리지 시스템의 백업 보호
* 운영 또는 2차 스토리지에서 공간 효율적인 백업 클론 생성
+
SnapManager를 사용하면 데이터베이스의 클론을 분할할 수 있습니다.


